%% Controller Robustness Comparison
% Final Tuned LQR vs Optimized Skyhook
%
% Step 11B
%
% Test:
% Symmetric bump at 72 km/h
%
% Parameter uncertainty cases:
% 1. Nominal
% 2. +10% sprung mass
% 3. -10% suspension stiffness
% 4. -10% damping
% 5. -10% tyre stiffness
%
% Controllers:
% controller_mode = 1 -> Final Tuned LQR
% controller_mode = 2 -> Optimized Skyhook
%
% All plots and results are automatically saved.

clear;
clc;
close all;

%% =========================================================
% Vehicle Parameters
% ==========================================================

run(fullfile(fileparts(fileparts(fileparts(mfilename('fullpath')))), ...
    'Scripts', '01_Parameters', 'vehicle_parameters.m'));

%% =========================================================
% Project Paths
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
plotsFolder = fullfile(projectFolder, 'Plots', 'Robustness');

if ~exist(plotsFolder,'dir')
    mkdir(plotsFolder);
end

%% =========================================================
% Load Final Tuned LQR
% ==========================================================

controllerFile = fullfile( ...
    lqrResultsFolder, ...
    'final_tuned_lqr_controller.mat');

if ~isfile(controllerFile)
    error( ...
        'Final tuned LQR controller file not found: %s', ...
        controllerFile);
end

controllerData = load(controllerFile);

K_lqr = controllerData.K_lqr_final;

%% =========================================================
% Controller Parameters
% ==========================================================

C_sky = 6000;           % Optimized Skyhook gain [N*s/m]

F_act_max = 3000;       % Actuator limit [N]
active_mode = 1;

assignin('base','K_lqr',K_lqr);
assignin('base','C_sky',C_sky);
assignin('base','F_act_max',F_act_max);
assignin('base','active_mode',active_mode);

%% =========================================================
% Symmetric Bump Test
% ==========================================================

V = 20;                 % m/s = 72 km/h

bump_duration = ...
    bump_length / V;

rear_delay = ...
    L / V;

t_bump_rear = ...
    t_bump_front + rear_delay;

assignin('base','V',V);
assignin('base','bump_duration',bump_duration);
assignin('base','rear_delay',rear_delay);
assignin('base','t_bump_rear',t_bump_rear);

%% =========================================================
% Store Nominal Parameters
% ==========================================================

nominal.m_s = m_s;

nominal.k_sf = k_sf;
nominal.k_sr = k_sr;

nominal.c_sf = c_sf;
nominal.c_sr = c_sr;

nominal.k_t = k_t;

%% =========================================================
% Controller Definitions
% ==========================================================

controllerNames = { ...
    'Final Tuned LQR'; ...
    'Optimized Skyhook'};

controllerModes = [ ...
    1; ...
    2];

nControllers = numel(controllerNames);

%% =========================================================
% Robustness Cases
% ==========================================================

caseNames = { ...
    'Nominal'; ...
    '+10% Sprung Mass'; ...
    '-10% Suspension Stiffness'; ...
    '-10% Damping'; ...
    '-10% Tyre Stiffness'};

nCases = numel(caseNames);

%% =========================================================
% Result Arrays
% ==========================================================

PeakHeave_mm = zeros(nCases,nControllers);

PeakPitch_deg = zeros(nCases,nControllers);

RMSHeaveAccel = zeros(nCases,nControllers);

RMSPitchAccel = zeros(nCases,nControllers);

SettlingTime_s = zeros(nCases,nControllers);

PeakForce_N = zeros(nCases,nControllers);

MeanRMSForce_N = zeros(nCases,nControllers);

MaxSaturation_pct = zeros(nCases,nControllers);

Stable = false(nCases,nControllers);

%% =========================================================
% Time-History Storage
% ==========================================================

timeHistory = cell(nCases,nControllers);

heaveHistory = cell(nCases,nControllers);

pitchHistory = cell(nCases,nControllers);

heaveAccelHistory = cell(nCases,nControllers);

pitchAccelHistory = cell(nCases,nControllers);

%% =========================================================
% Simulink Model
% ==========================================================

modelName = ...
    'RaceCar_7DOF_ActiveSuspension';

modelFile = fullfile( ...
    projectFolder, ...
    'Model', ...
    [modelName '.slx']);

if ~isfile(modelFile)

    error( ...
        'Simulink model not found: %s', ...
        modelFile);

end

load_system(modelFile);

%% =========================================================
% Begin Robustness Comparison
% ==========================================================

disp('====================================================')
disp('CONTROLLER ROBUSTNESS COMPARISON')
disp('FINAL LQR vs OPTIMIZED SKYHOOK')
disp('====================================================')

for controllerIdx = 1:nControllers

    %% -----------------------------------------------------
    % Controller Selection
    % ------------------------------------------------------

    controller_mode = ...
        controllerModes(controllerIdx);

    assignin( ...
        'base', ...
        'controller_mode', ...
        controller_mode);

    fprintf('\n====================================================\n');

    fprintf( ...
        'CONTROLLER: %s\n', ...
        controllerNames{controllerIdx});

    fprintf('====================================================\n');

    for caseIdx = 1:nCases

        %% -------------------------------------------------
        % Restore Nominal Values
        % --------------------------------------------------

        m_s_case = ...
            nominal.m_s;

        k_sf_case = ...
            nominal.k_sf;

        k_sr_case = ...
            nominal.k_sr;

        c_sf_case = ...
            nominal.c_sf;

        c_sr_case = ...
            nominal.c_sr;

        k_t_case = ...
            nominal.k_t;

        %% -------------------------------------------------
        % Apply Parameter Uncertainty
        % --------------------------------------------------

        switch caseIdx

            case 1

                % Nominal

            case 2

                % +10% sprung mass

                m_s_case = ...
                    1.10 * nominal.m_s;

            case 3

                % -10% suspension stiffness

                k_sf_case = ...
                    0.90 * nominal.k_sf;

                k_sr_case = ...
                    0.90 * nominal.k_sr;

            case 4

                % -10% suspension damping

                c_sf_case = ...
                    0.90 * nominal.c_sf;

                c_sr_case = ...
                    0.90 * nominal.c_sr;

            case 5

                % -10% tyre stiffness

                k_t_case = ...
                    0.90 * nominal.k_t;

        end

        %% -------------------------------------------------
        % Push Parameters to Simulink
        % --------------------------------------------------

        assignin( ...
            'base', ...
            'm_s', ...
            m_s_case);

        assignin( ...
            'base', ...
            'k_sf', ...
            k_sf_case);

        assignin( ...
            'base', ...
            'k_sr', ...
            k_sr_case);

        assignin( ...
            'base', ...
            'c_sf', ...
            c_sf_case);

        assignin( ...
            'base', ...
            'c_sr', ...
            c_sr_case);

        assignin( ...
            'base', ...
            'k_t', ...
            k_t_case);

        assignin( ...
            'base', ...
            'K_lqr', ...
            K_lqr);

        assignin( ...
            'base', ...
            'C_sky', ...
            C_sky);

        assignin( ...
            'base', ...
            'active_mode', ...
            active_mode);

        assignin( ...
            'base', ...
            'F_act_max', ...
            F_act_max);

        %% -------------------------------------------------
        % Status
        % --------------------------------------------------

        fprintf( ...
            '\n%s | Case %d/%d: %s\n', ...
            controllerNames{controllerIdx}, ...
            caseIdx, ...
            nCases, ...
            caseNames{caseIdx});

        %% -------------------------------------------------
        % Simulation
        % --------------------------------------------------

        simOut = sim( ...
            modelName, ...
            'StopTime', ...
            '5', ...
            'ReturnWorkspaceOutputs', ...
            'on');

        %% -------------------------------------------------
        % Logged Signals
        % --------------------------------------------------

        zs = getLoggedSignal( ...
            simOut, ...
            'z_s_out');

        theta = getLoggedSignal( ...
            simOut, ...
            'theta_out');

        zsDDot = getLoggedSignal( ...
            simOut, ...
            'z_s_ddot_out');

        thetaDDot = getLoggedSignal( ...
            simOut, ...
            'theta_ddot_out');

        FLforce = getLoggedSignal( ...
            simOut, ...
            'F_act_FL_out');

        FRforce = getLoggedSignal( ...
            simOut, ...
            'F_act_FR_out');

        RLforce = getLoggedSignal( ...
            simOut, ...
            'F_act_RL_out');

        RRforce = getLoggedSignal( ...
            simOut, ...
            'F_act_RR_out');

        %% -------------------------------------------------
        % Extract Data
        % --------------------------------------------------

        t = zs.Time;

        heave = ...
            zs.Data;

        pitch = ...
            rad2deg(theta.Data);

        heaveAccel = ...
            zsDDot.Data;

        pitchAccel = ...
            rad2deg(thetaDDot.Data);

        F_FL = ...
            FLforce.Data;

        F_FR = ...
            FRforce.Data;

        F_RL = ...
            RLforce.Data;

        F_RR = ...
            RRforce.Data;

        %% -------------------------------------------------
        % Performance Metrics
        % --------------------------------------------------

        PeakHeave_mm(caseIdx,controllerIdx) = ...
            1000 * max(abs(heave));

        PeakPitch_deg(caseIdx,controllerIdx) = ...
            max(abs(pitch));

        RMSHeaveAccel(caseIdx,controllerIdx) = ...
            rms(heaveAccel);

        RMSPitchAccel(caseIdx,controllerIdx) = ...
            rms(pitchAccel);

        PeakForce_N(caseIdx,controllerIdx) = ...
            max([ ...
            max(abs(F_FL)), ...
            max(abs(F_FR)), ...
            max(abs(F_RL)), ...
            max(abs(F_RR))]);

        rmsForceCorners = [ ...
            rms(F_FL), ...
            rms(F_FR), ...
            rms(F_RL), ...
            rms(F_RR)];

        MeanRMSForce_N(caseIdx,controllerIdx) = ...
            mean(rmsForceCorners);

        %% -------------------------------------------------
        % Saturation
        % --------------------------------------------------

        saturationCorners = 100 * [ ...
            mean(abs(F_FL) >= 0.999*F_act_max), ...
            mean(abs(F_FR) >= 0.999*F_act_max), ...
            mean(abs(F_RL) >= 0.999*F_act_max), ...
            mean(abs(F_RR) >= 0.999*F_act_max)];

        MaxSaturation_pct(caseIdx,controllerIdx) = ...
            max(saturationCorners);

        %% -------------------------------------------------
        % Settling Time
        % --------------------------------------------------

        peakHeave_m = ...
            max(abs(heave));

        settlingTolerance = ...
            max( ...
            0.02 * peakHeave_m, ...
            1e-5);

        eventEndTime = ...
            t_bump_rear + bump_duration;

        postEventIdx = ...
            find(t >= eventEndTime);

        heavePost = ...
            abs(heave(postEventIdx));

        lastOutside = ...
            find( ...
            heavePost > settlingTolerance, ...
            1, ...
            'last');

        if isempty(lastOutside)

            SettlingTime_s(caseIdx,controllerIdx) = ...
                eventEndTime;

        else

            globalIdx = ...
                postEventIdx(lastOutside);

            SettlingTime_s(caseIdx,controllerIdx) = ...
                t(globalIdx);

        end

        %% -------------------------------------------------
        % Simulation Stability
        % --------------------------------------------------

        finiteCheck = ...
            all(isfinite(heave)) && ...
            all(isfinite(pitch)) && ...
            all(isfinite(heaveAccel)) && ...
            all(isfinite(pitchAccel)) && ...
            all(isfinite(F_FL)) && ...
            all(isfinite(F_FR)) && ...
            all(isfinite(F_RL)) && ...
            all(isfinite(F_RR));

        boundedCheck = ...
            PeakHeave_mm(caseIdx,controllerIdx) < 100 && ...
            PeakPitch_deg(caseIdx,controllerIdx) < 10 && ...
            PeakForce_N(caseIdx,controllerIdx) ...
            <= 1.01*F_act_max;

        Stable(caseIdx,controllerIdx) = ...
            finiteCheck && boundedCheck;

        %% -------------------------------------------------
        % Time Histories
        % --------------------------------------------------

        timeHistory{caseIdx,controllerIdx} = ...
            t;

        heaveHistory{caseIdx,controllerIdx} = ...
            1000*heave;

        pitchHistory{caseIdx,controllerIdx} = ...
            pitch;

        heaveAccelHistory{caseIdx,controllerIdx} = ...
            heaveAccel;

        pitchAccelHistory{caseIdx,controllerIdx} = ...
            pitchAccel;

        %% -------------------------------------------------
        % Console Result
        % --------------------------------------------------

        fprintf( ...
            ['Peak heave = %.4f mm | ' ...
             'Peak pitch = %.5f deg | ' ...
             'RMS heave accel = %.4f m/s^2 | ' ...
             'Peak force = %.1f N\n'], ...
            PeakHeave_mm(caseIdx,controllerIdx), ...
            PeakPitch_deg(caseIdx,controllerIdx), ...
            RMSHeaveAccel(caseIdx,controllerIdx), ...
            PeakForce_N(caseIdx,controllerIdx));

    end
end

%% =========================================================
% Restore Nominal Parameters
% ==========================================================

assignin('base','m_s',nominal.m_s);

assignin('base','k_sf',nominal.k_sf);
assignin('base','k_sr',nominal.k_sr);

assignin('base','c_sf',nominal.c_sf);
assignin('base','c_sr',nominal.c_sr);

assignin('base','k_t',nominal.k_t);

assignin('base','K_lqr',K_lqr);
assignin('base','C_sky',C_sky);

%% =========================================================
% Sensitivity Relative to Each Controller's Nominal Case
% ==========================================================

heaveSensitivity_pct = zeros(nCases,nControllers);
pitchSensitivity_pct = zeros(nCases,nControllers);

heaveAccelSensitivity_pct = zeros(nCases,nControllers);
pitchAccelSensitivity_pct = zeros(nCases,nControllers);

settlingSensitivity_pct = zeros(nCases,nControllers);
forceSensitivity_pct = zeros(nCases,nControllers);

for c = 1:nControllers

    heaveSensitivity_pct(:,c) = ...
        100 * ...
        (PeakHeave_mm(:,c) / PeakHeave_mm(1,c) - 1);

    pitchSensitivity_pct(:,c) = ...
        100 * ...
        (PeakPitch_deg(:,c) / PeakPitch_deg(1,c) - 1);

    heaveAccelSensitivity_pct(:,c) = ...
        100 * ...
        (RMSHeaveAccel(:,c) / RMSHeaveAccel(1,c) - 1);

    pitchAccelSensitivity_pct(:,c) = ...
        100 * ...
        (RMSPitchAccel(:,c) / RMSPitchAccel(1,c) - 1);

    settlingSensitivity_pct(:,c) = ...
        100 * ...
        (SettlingTime_s(:,c) / SettlingTime_s(1,c) - 1);

    forceSensitivity_pct(:,c) = ...
        100 * ...
        (PeakForce_N(:,c) / PeakForce_N(1,c) - 1);

end

%% =========================================================
% Robustness Score
% ==========================================================
%
% Mean absolute parameter sensitivity.
% Nominal case is excluded.
%
% Lower score = less sensitive to parameter variation.

robustnessScore = zeros(nControllers,1);

for c = 1:nControllers

    variations = 2:nCases;

    metricSensitivity = [ ...
        abs(heaveSensitivity_pct(variations,c)), ...
        abs(pitchSensitivity_pct(variations,c)), ...
        abs(heaveAccelSensitivity_pct(variations,c)), ...
        abs(pitchAccelSensitivity_pct(variations,c)), ...
        abs(settlingSensitivity_pct(variations,c)), ...
        abs(forceSensitivity_pct(variations,c))];

    robustnessScore(c) = ...
        mean(metricSensitivity(:));

end

%% =========================================================
% Results Table
% ==========================================================

tableController = {};
tableCase = {};

tablePeakHeave = [];
tablePeakPitch = [];

tableRMSHeave = [];
tableRMSPitch = [];

tableSettling = [];
tablePeakForce = [];

tableMeanRMSForce = [];
tableSaturation = [];

tableStable = [];

for c = 1:nControllers

    for k = 1:nCases

        tableController{end+1,1} = ...
            controllerNames{c};

        tableCase{end+1,1} = ...
            caseNames{k};

        tablePeakHeave(end+1,1) = ...
            PeakHeave_mm(k,c);

        tablePeakPitch(end+1,1) = ...
            PeakPitch_deg(k,c);

        tableRMSHeave(end+1,1) = ...
            RMSHeaveAccel(k,c);

        tableRMSPitch(end+1,1) = ...
            RMSPitchAccel(k,c);

        tableSettling(end+1,1) = ...
            SettlingTime_s(k,c);

        tablePeakForce(end+1,1) = ...
            PeakForce_N(k,c);

        tableMeanRMSForce(end+1,1) = ...
            MeanRMSForce_N(k,c);

        tableSaturation(end+1,1) = ...
            MaxSaturation_pct(k,c);

        tableStable(end+1,1) = ...
            Stable(k,c);

    end
end

comparisonTable = table( ...
    tableController, ...
    tableCase, ...
    tablePeakHeave, ...
    tablePeakPitch, ...
    tableRMSHeave, ...
    tableRMSPitch, ...
    tableSettling, ...
    tablePeakForce, ...
    tableMeanRMSForce, ...
    tableSaturation, ...
    tableStable, ...
    'VariableNames',{ ...
    'Controller', ...
    'Case', ...
    'PeakHeave_mm', ...
    'PeakPitch_deg', ...
    'RMSHeaveAccel_mps2', ...
    'RMSPitchAccel_degps2', ...
    'SettlingTime_s', ...
    'PeakActuatorForce_N', ...
    'MeanRMSActuatorForce_N', ...
    'MaxSaturation_pct', ...
    'Stable'});

%% =========================================================
% Robustness Summary Table
% ==========================================================

robustnessSummary = table( ...
    controllerNames, ...
    robustnessScore, ...
    all(Stable,1)', ...
    max(PeakForce_N,[],1)', ...
    max(MaxSaturation_pct,[],1)', ...
    'VariableNames',{ ...
    'Controller', ...
    'MeanAbsSensitivity_pct', ...
    'AllCasesStable', ...
    'WorstPeakForce_N', ...
    'WorstSaturation_pct'});

%% =========================================================
% Display
% ==========================================================

disp(' ')
disp('====================================================')
disp('CONTROLLER ROBUSTNESS COMPARISON RESULTS')
disp('====================================================')

disp(comparisonTable)

disp(' ')
disp('====================================================')
disp('ROBUSTNESS SUMMARY')
disp('====================================================')

disp(robustnessSummary)

%% =========================================================
% Determine Most Robust Controller
% ==========================================================

[bestScore,bestIdx] = ...
    min(robustnessScore);

fprintf( ...
    '\nLowest parameter sensitivity: %s\n', ...
    controllerNames{bestIdx});

fprintf( ...
    'Mean absolute sensitivity = %.3f %%\n', ...
    bestScore);

%% =========================================================
% Save Main CSV
% ==========================================================

csvFile = fullfile( ...
    resultsFolder, ...
    'controller_robustness_comparison.csv');

writetable( ...
    comparisonTable, ...
    csvFile);

%% =========================================================
% Save Summary CSV
% ==========================================================

summaryCSV = fullfile( ...
    resultsFolder, ...
    'controller_robustness_summary.csv');

writetable( ...
    robustnessSummary, ...
    summaryCSV);

%% =========================================================
% Save MAT
% ==========================================================

matFile = fullfile( ...
    resultsFolder, ...
    'controller_robustness_comparison.mat');

save( ...
    matFile, ...
    'comparisonTable', ...
    'robustnessSummary', ...
    'PeakHeave_mm', ...
    'PeakPitch_deg', ...
    'RMSHeaveAccel', ...
    'RMSPitchAccel', ...
    'SettlingTime_s', ...
    'PeakForce_N', ...
    'MeanRMSForce_N', ...
    'MaxSaturation_pct', ...
    'Stable', ...
    'heaveSensitivity_pct', ...
    'pitchSensitivity_pct', ...
    'heaveAccelSensitivity_pct', ...
    'pitchAccelSensitivity_pct', ...
    'settlingSensitivity_pct', ...
    'forceSensitivity_pct', ...
    'robustnessScore', ...
    'timeHistory', ...
    'heaveHistory', ...
    'pitchHistory', ...
    'heaveAccelHistory', ...
    'pitchAccelHistory');

%% =========================================================
% Save TXT
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'controller_robustness_comparison.txt');

fid = fopen(txtFile,'w');

if fid == -1
    error('Unable to create robustness comparison TXT.');
end

fprintf(fid, ...
    'FINAL CONTROLLER ROBUSTNESS COMPARISON\n');

fprintf(fid, ...
    '======================================\n\n');

fprintf(fid, ...
    'Symmetric bump speed = %.1f km/h\n\n', ...
    3.6*V);

for c = 1:nControllers

    fprintf(fid, ...
        '%s\n', ...
        upper(controllerNames{c}));

    fprintf(fid, ...
        '--------------------------------------\n');

    for k = 1:nCases

        fprintf(fid, ...
            '%s\n', ...
            caseNames{k});

        fprintf(fid, ...
            'Peak heave = %.4f mm\n', ...
            PeakHeave_mm(k,c));

        fprintf(fid, ...
            'Peak pitch = %.5f deg\n', ...
            PeakPitch_deg(k,c));

        fprintf(fid, ...
            'RMS heave acceleration = %.5f m/s^2\n', ...
            RMSHeaveAccel(k,c));

        fprintf(fid, ...
            'RMS pitch acceleration = %.5f deg/s^2\n', ...
            RMSPitchAccel(k,c));

        fprintf(fid, ...
            'Settling time = %.4f s\n', ...
            SettlingTime_s(k,c));

        fprintf(fid, ...
            'Peak actuator force = %.2f N\n', ...
            PeakForce_N(k,c));

        fprintf(fid, ...
            'Maximum saturation = %.4f %%\n', ...
            MaxSaturation_pct(k,c));

        fprintf(fid, ...
            'Stable = %d\n\n', ...
            Stable(k,c));

    end

    fprintf(fid, ...
        'Mean absolute sensitivity = %.4f %%\n\n', ...
        robustnessScore(c));

end

fprintf(fid, ...
    'MOST ROBUST CONTROLLER\n');

fprintf(fid, ...
    '--------------------------------------\n');

fprintf(fid, ...
    '%s\n', ...
    controllerNames{bestIdx});

fprintf(fid, ...
    'Mean absolute sensitivity = %.4f %%\n', ...
    bestScore);

fclose(fid);

%% =========================================================
% Plot 1 - Peak Body Motion
% ==========================================================

fig1 = figure( ...
    'Name', ...
    'Controller Robustness - Body Motion', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

bar(PeakHeave_mm)

grid on

ylabel('Peak Heave [mm]')
title('Peak Heave Under Parameter Uncertainty')

xticks(1:nCases)
xticklabels(caseNames)
xtickangle(15)

legend( ...
    controllerNames, ...
    'Location', ...
    'best');

subplot(2,1,2)

bar(PeakPitch_deg)

grid on

ylabel('Peak Pitch [deg]')
xlabel('Parameter Case')

title('Peak Pitch Under Parameter Uncertainty')

xticks(1:nCases)
xticklabels(caseNames)
xtickangle(15)

legend( ...
    controllerNames, ...
    'Location', ...
    'best');

bodyPNG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_body_motion.png');

bodyFIG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_body_motion.fig');

exportgraphics( ...
    fig1, ...
    bodyPNG, ...
    'Resolution',300);

savefig(fig1,bodyFIG);

%% =========================================================
% Plot 2 - Ride Acceleration
% ==========================================================

fig2 = figure( ...
    'Name', ...
    'Controller Robustness - Acceleration', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

bar(RMSHeaveAccel)

grid on

ylabel('RMS Heave Accel [m/s^2]')

title( ...
    'RMS Heave Acceleration Under Parameter Uncertainty');

xticks(1:nCases)
xticklabels(caseNames)
xtickangle(15)

legend( ...
    controllerNames, ...
    'Location', ...
    'best');

subplot(2,1,2)

bar(RMSPitchAccel)

grid on

ylabel('RMS Pitch Accel [deg/s^2]')
xlabel('Parameter Case')

title( ...
    'RMS Pitch Acceleration Under Parameter Uncertainty');

xticks(1:nCases)
xticklabels(caseNames)
xtickangle(15)

legend( ...
    controllerNames, ...
    'Location', ...
    'best');

accelPNG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_acceleration.png');

accelFIG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_acceleration.fig');

exportgraphics( ...
    fig2, ...
    accelPNG, ...
    'Resolution',300);

savefig(fig2,accelFIG);

%% =========================================================
% Plot 3 - Peak Actuator Demand
% ==========================================================

fig3 = figure( ...
    'Name', ...
    'Controller Robustness - Actuator Demand', ...
    'NumberTitle', ...
    'off');

bar(PeakForce_N)

hold on

yline( ...
    F_act_max, ...
    '--', ...
    'Actuator Limit');

grid on

ylabel('Peak Actuator Force [N]')
xlabel('Parameter Case')

title( ...
    'Peak Actuator Demand Under Parameter Uncertainty');

xticks(1:nCases)
xticklabels(caseNames)
xtickangle(15)

legend( ...
    controllerNames, ...
    'Location', ...
    'best');

ylim([0 1.1*F_act_max]);

forcePNG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_actuator_force.png');

forceFIG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_actuator_force.fig');

exportgraphics( ...
    fig3, ...
    forcePNG, ...
    'Resolution',300);

savefig(fig3,forceFIG);

%% =========================================================
% Plot 4 - Parameter Sensitivity
% ==========================================================

fig4 = figure( ...
    'Name', ...
    'Controller Robustness - Sensitivity', ...
    'NumberTitle', ...
    'off');

bar(robustnessScore)

grid on

ylabel('Mean Absolute Sensitivity [%]')

title( ...
    'Controller Sensitivity to Parameter Uncertainty');

xticks(1:nControllers)

xticklabels(controllerNames)

sensitivityPNG = fullfile( ...
    projectFolder, 'Plots', 'Final', ...
    'controller_robustness_sensitivity.png');

sensitivityFIG = fullfile( ...
    projectFolder, 'Plots', 'Final', ...
    'controller_robustness_sensitivity.fig');

exportgraphics( ...
    fig4, ...
    sensitivityPNG, ...
    'Resolution',300);

savefig(fig4,sensitivityFIG);

%% =========================================================
% Plot 5 - Nominal-Normalized Peak Metrics
% ==========================================================

normalizedHeave = zeros(nCases,nControllers);
normalizedPitch = zeros(nCases,nControllers);
normalizedForce = zeros(nCases,nControllers);

for c = 1:nControllers

    normalizedHeave(:,c) = ...
        PeakHeave_mm(:,c) / PeakHeave_mm(1,c);

    normalizedPitch(:,c) = ...
        PeakPitch_deg(:,c) / PeakPitch_deg(1,c);

    normalizedForce(:,c) = ...
        PeakForce_N(:,c) / PeakForce_N(1,c);

end

fig5 = figure( ...
    'Name', ...
    'Controller Robustness - Normalized', ...
    'NumberTitle', ...
    'off');

subplot(3,1,1)

plot( ...
    1:nCases, ...
    normalizedHeave(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on

plot( ...
    1:nCases, ...
    normalizedHeave(:,2), ...
    '-o', ...
    'LineWidth',1.2);

yline(1,'--');

grid on

ylabel('Relative Heave')
title('Normalized Peak Heave')

legend( ...
    controllerNames, ...
    'Location','best');

subplot(3,1,2)

plot( ...
    1:nCases, ...
    normalizedPitch(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on

plot( ...
    1:nCases, ...
    normalizedPitch(:,2), ...
    '-o', ...
    'LineWidth',1.2);

yline(1,'--');

grid on

ylabel('Relative Pitch')
title('Normalized Peak Pitch')

subplot(3,1,3)

plot( ...
    1:nCases, ...
    normalizedForce(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on

plot( ...
    1:nCases, ...
    normalizedForce(:,2), ...
    '-o', ...
    'LineWidth',1.2);

yline(1,'--');

grid on

ylabel('Relative Force')
xlabel('Parameter Case')

title('Normalized Peak Actuator Force')

xticks(1:nCases)
xticklabels(caseNames)
xtickangle(15)

normalizedPNG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_normalized_metrics.png');

normalizedFIG = fullfile( ...
    plotsFolder, ...
    'controller_robustness_normalized_metrics.fig');

exportgraphics( ...
    fig5, ...
    normalizedPNG, ...
    'Resolution',300);

savefig(fig5,normalizedFIG);

%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('====================================================')
disp('CONTROLLER ROBUSTNESS COMPARISON SAVED')
disp('====================================================')

fprintf('\nResults:\n');

fprintf('%s\n',txtFile);
fprintf('%s\n',csvFile);
fprintf('%s\n',summaryCSV);
fprintf('%s\n',matFile);

fprintf('\nPlots:\n');

fprintf('%s\n',bodyPNG);
fprintf('%s\n',accelPNG);
fprintf('%s\n',forcePNG);
fprintf('%s\n',sensitivityPNG);
fprintf('%s\n',normalizedPNG);

%% =========================================================
% Helper Function
% Keep local function at END of script.
% ==========================================================

function sig = getLoggedSignal(simOut,signalName)

    try

        sig = simOut.get(signalName);

        if ~isempty(sig)
            return;
        end

    catch
    end

    if evalin( ...
            'base', ...
            sprintf( ...
            'exist(''%s'',''var'')', ...
            signalName))

        sig = evalin( ...
            'base', ...
            signalName);

        return;

    end

    error( ...
        'Unable to locate logged signal: %s', ...
        signalName);

end
