%% Final Tuned LQR - Working Range Assessment
% Evaluates:
% - Suspension deflection
% - Suspension relative velocity
% - Tyre deflection
% - Tyre normal-load/contact condition
% - Actuator loading
%
% Operating condition:
% 144 km/h asymmetric left-side kerb

clear;
clc;

%% =========================================================
% Vehicle Parameters
% ==========================================================

run(fullfile(fileparts(fileparts(fileparts(mfilename('fullpath')))), ...
    'Scripts', '01_Parameters', 'vehicle_parameters.m'));

%% =========================================================
% Project Paths
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
plotsFolder = fullfile(projectFolder, 'Plots', 'Operating_Envelope');

if ~exist(plotsFolder, 'dir')
    mkdir(plotsFolder);
end

%% =========================================================
% Load Final Tuned LQR
% ==========================================================

controllerFile = fullfile( ...
    lqrResultsFolder, ...
    'final_tuned_lqr_controller.mat');

if ~isfile(controllerFile)
    error('final_tuned_lqr_controller.mat not found.');
end

controllerData = load(controllerFile);

K_lqr = controllerData.K_lqr_final;

active_mode = 1;
F_act_max = 3000;

%% =========================================================
% High-Speed Kerb Operating Point
% ==========================================================

V = 40;                  % [m/s] = 144 km/h

kerb_duration = ...
    kerb_length / V;

rear_delay = ...
    L / V;

t_kerb_rear = ...
    t_kerb_front + rear_delay;

%% =========================================================
% Push Variables to Simulink
% ==========================================================

assignin('base','V',V);

assignin( ...
    'base', ...
    'kerb_duration', ...
    kerb_duration);

assignin( ...
    'base', ...
    'rear_delay', ...
    rear_delay);

assignin( ...
    'base', ...
    't_kerb_rear', ...
    t_kerb_rear);

assignin( ...
    'base', ...
    'K_lqr', ...
    K_lqr);

assignin( ...
    'base', ...
    'active_mode', ...
    active_mode);

assignin( ...
    'base', ...
    'F_act_max', ...
    F_act_max);

%% =========================================================
% Model
% ==========================================================

modelName = ...
    'RaceCar_7DOF_ActiveSuspension';

modelFile = fullfile( ...
    projectFolder, ...
    'Model', ...
    [modelName '.slx']);

if ~isfile(modelFile)
    error('Simulink model not found: %s', modelFile);
end

load_system(modelFile);

%% =========================================================
% Simulate
% ==========================================================

disp('====================================================')
disp('LQR WORKING-RANGE ASSESSMENT - 144 km/h KERB')
disp('====================================================')

simOut = sim( ...
    modelName, ...
    'StopTime', ...
    '5', ...
    'ReturnWorkspaceOutputs', ...
    'on');

%% =========================================================
% Signals
% ==========================================================

zs = getLoggedSignal( ...
    simOut, ...
    'z_s_out');

theta = getLoggedSignal( ...
    simOut, ...
    'theta_out');

phi = getLoggedSignal( ...
    simOut, ...
    'phi_out');

zsDot = getLoggedSignal( ...
    simOut, ...
    'z_s_dot');

thetaDot = getLoggedSignal( ...
    simOut, ...
    'theta_dot');

phiDot = getLoggedSignal( ...
    simOut, ...
    'phi_dot');

zuFL = getLoggedSignal( ...
    simOut, ...
    'z_u_FL_out');

zuFR = getLoggedSignal( ...
    simOut, ...
    'z_u_FR_out');

zuRL = getLoggedSignal( ...
    simOut, ...
    'z_u_RL_out');

zuRR = getLoggedSignal( ...
    simOut, ...
    'z_u_RR_out');

zuFLDot = getLoggedSignal( ...
    simOut, ...
    'z_u_FL_dot');

zuFRDot = getLoggedSignal( ...
    simOut, ...
    'z_u_FR_dot');

zuRLDot = getLoggedSignal( ...
    simOut, ...
    'z_u_RL_dot');

zuRRDot = getLoggedSignal( ...
    simOut, ...
    'z_u_RR_dot');

FLforce = getLoggedSignal( ...
    simOut, ...
    'F_act_FL_out');

FRforce = getLoggedSignal( ...
    simOut, ...
    'F_act_FR_out');

RLforce = getLoggedSignal( ...
    simOut, ...
    'F_act_RL_out');

RRforce = getLoggedSignal( ...
    simOut, ...
    'F_act_RR_out');

%% =========================================================
% Time
% ==========================================================

t = zs.Time;

%% =========================================================
% Body Corner Displacements
% ==========================================================
%
% Internal angular states are radians.
%
% FL = z_s + a*theta + tf/2*phi
% FR = z_s + a*theta - tf/2*phi
% RL = z_s - b*theta + tr/2*phi
% RR = z_s - b*theta - tr/2*phi

zBodyFL = ...
      zs.Data ...
    + a * theta.Data ...
    + (t_f/2) * phi.Data;

zBodyFR = ...
      zs.Data ...
    + a * theta.Data ...
    - (t_f/2) * phi.Data;

zBodyRL = ...
      zs.Data ...
    - b * theta.Data ...
    + (t_r/2) * phi.Data;

zBodyRR = ...
      zs.Data ...
    - b * theta.Data ...
    - (t_r/2) * phi.Data;

%% =========================================================
% Body Corner Velocities
% ==========================================================

zBodyDotFL = ...
      zsDot.Data ...
    + a * thetaDot.Data ...
    + (t_f/2) * phiDot.Data;

zBodyDotFR = ...
      zsDot.Data ...
    + a * thetaDot.Data ...
    - (t_f/2) * phiDot.Data;

zBodyDotRL = ...
      zsDot.Data ...
    - b * thetaDot.Data ...
    + (t_r/2) * phiDot.Data;

zBodyDotRR = ...
      zsDot.Data ...
    - b * thetaDot.Data ...
    - (t_r/2) * phiDot.Data;

%% =========================================================
% Suspension Deflections
% ==========================================================

deltaFL = ...
    zBodyFL - zuFL.Data;

deltaFR = ...
    zBodyFR - zuFR.Data;

deltaRL = ...
    zBodyRL - zuRL.Data;

deltaRR = ...
    zBodyRR - zuRR.Data;

%% =========================================================
% Suspension Relative Velocities
% ==========================================================

deltaDotFL = ...
    zBodyDotFL - zuFLDot.Data;

deltaDotFR = ...
    zBodyDotFR - zuFRDot.Data;

deltaDotRL = ...
    zBodyDotRL - zuRLDot.Data;

deltaDotRR = ...
    zBodyDotRR - zuRRDot.Data;

%% =========================================================
% Reconstruct Road Inputs
% ==========================================================
%
% Left-side kerb:
% FL and RL excited
% FR and RR remain flat

zrFL = zeros(size(t));
zrFR = zeros(size(t));
zrRL = zeros(size(t));
zrRR = zeros(size(t));

frontMask = ...
    (t >= t_kerb_front) & ...
    (t <= t_kerb_front + kerb_duration);

rearMask = ...
    (t >= t_kerb_rear) & ...
    (t <= t_kerb_rear + kerb_duration);

% Half-sine front-left kerb
zrFL(frontMask) = ...
    kerb_height .* ...
    sin( ...
        pi .* ...
        (t(frontMask) - t_kerb_front) ./ ...
        kerb_duration);

% Half-sine rear-left kerb
zrRL(rearMask) = ...
    kerb_height .* ...
    sin( ...
        pi .* ...
        (t(rearMask) - t_kerb_rear) ./ ...
        kerb_duration);

%% =========================================================
% Tyre Deflections
% ==========================================================
%
% Positive tyreDef means wheel centre is above road
% relative to equilibrium coordinate convention.

tyreDefFL = ...
    zuFL.Data - zrFL;

tyreDefFR = ...
    zuFR.Data - zrFR;

tyreDefRL = ...
    zuRL.Data - zrRL;

tyreDefRR = ...
    zuRR.Data - zrRR;

%% =========================================================
% Corner Labels
% ==========================================================

cornerNames = { ...
    'FL'; ...
    'FR'; ...
    'RL'; ...
    'RR'};

%% =========================================================
% Working-Range Peak Metrics
% ==========================================================

PeakSuspDeflection_mm = 1000 * [ ...
    max(abs(deltaFL)); ...
    max(abs(deltaFR)); ...
    max(abs(deltaRL)); ...
    max(abs(deltaRR))];

PeakSuspVelocity_mps = [ ...
    max(abs(deltaDotFL)); ...
    max(abs(deltaDotFR)); ...
    max(abs(deltaDotRL)); ...
    max(abs(deltaDotRR))];

PeakTyreDeflection_mm = 1000 * [ ...
    max(abs(tyreDefFL)); ...
    max(abs(tyreDefFR)); ...
    max(abs(tyreDefRL)); ...
    max(abs(tyreDefRR))];

PeakActuatorForce_N = [ ...
    max(abs(FLforce.Data)); ...
    max(abs(FRforce.Data)); ...
    max(abs(RLforce.Data)); ...
    max(abs(RRforce.Data))];

ActuatorUtilization_pct = ...
    100 * PeakActuatorForce_N / F_act_max;

%% =========================================================
% Working-Range Table
% ==========================================================

workingRangeTable = table( ...
    cornerNames, ...
    PeakSuspDeflection_mm, ...
    PeakSuspVelocity_mps, ...
    PeakTyreDeflection_mm, ...
    PeakActuatorForce_N, ...
    ActuatorUtilization_pct, ...
    'VariableNames', { ...
    'Corner', ...
    'PeakSuspDeflection_mm', ...
    'PeakSuspVelocity_mps', ...
    'PeakTyreDeflection_mm', ...
    'PeakActuatorForce_N', ...
    'ActuatorUtilization_pct'});

%% =========================================================
% Tyre Contact / Normal Load Check
% ==========================================================
%
% Model is linearized around static equilibrium.
%
% Total tyre normal load:
%
% Fz = Fz_static - k_t * (z_u - z_r)
%
% A negative Fz indicates the linear tyre spring is
% predicting tensile force, which physically means the
% tyre would have unloaded / lost road contact.

Fz0_FL = F_FL_static;
Fz0_FR = F_FR_static;
Fz0_RL = F_RL_static;
Fz0_RR = F_RR_static;

Fz_FL = ...
    Fz0_FL - k_t * tyreDefFL;

Fz_FR = ...
    Fz0_FR - k_t * tyreDefFR;

Fz_RL = ...
    Fz0_RL - k_t * tyreDefRL;

Fz_RR = ...
    Fz0_RR - k_t * tyreDefRR;

%% =========================================================
% Tyre Load Metrics
% ==========================================================

MinFz_N = [ ...
    min(Fz_FL); ...
    min(Fz_FR); ...
    min(Fz_RL); ...
    min(Fz_RR)];

MaxFz_N = [ ...
    max(Fz_FL); ...
    max(Fz_FR); ...
    max(Fz_RL); ...
    max(Fz_RR)];

ContactLoss_pct = 100 * [ ...
    mean(Fz_FL <= 0); ...
    mean(Fz_FR <= 0); ...
    mean(Fz_RL <= 0); ...
    mean(Fz_RR <= 0)];

tyreContactTable = table( ...
    cornerNames, ...
    MinFz_N, ...
    MaxFz_N, ...
    ContactLoss_pct, ...
    'VariableNames', { ...
    'Corner', ...
    'MinimumNormalLoad_N', ...
    'MaximumNormalLoad_N', ...
    'ContactLoss_pct'});

%% =========================================================
% Display Working-Range Results
% ==========================================================

disp(' ')
disp('====================================================')
disp('WORKING-RANGE RESULTS')
disp('====================================================')

disp(workingRangeTable)

fprintf( ...
    '\nMaximum suspension deflection = %.3f mm\n', ...
    max(PeakSuspDeflection_mm));

fprintf( ...
    'Maximum suspension velocity   = %.3f m/s\n', ...
    max(PeakSuspVelocity_mps));

fprintf( ...
    'Maximum tyre deflection       = %.3f mm\n', ...
    max(PeakTyreDeflection_mm));

fprintf( ...
    'Maximum actuator utilization  = %.2f %%\n', ...
    max(ActuatorUtilization_pct));

%% =========================================================
% Display Tyre Contact Results
% ==========================================================

disp(' ')
disp('====================================================')
disp('TYRE CONTACT CHECK')
disp('====================================================')

disp(tyreContactTable)

fprintf( ...
    '\nMinimum normal load across vehicle = %.2f N\n', ...
    min(MinFz_N));

fprintf( ...
    'Maximum contact-loss duration = %.4f %%\n', ...
    max(ContactLoss_pct));

%% =========================================================
% Contact Assessment
% ==========================================================

if all(MinFz_N > 0)

    tyreContactResult = ...
        'PASS - all tyres remain positively loaded.';

else

    tyreContactResult = ...
        ['WARNING - one or more tyres reach zero/negative ' ...
         'predicted normal load.'];

end

fprintf( ...
    'Tyre contact result: %s\n', ...
    tyreContactResult);

%% =========================================================
% Save Working-Range CSV
% ==========================================================

csvFile = fullfile( ...
    resultsFolder, ...
    'lqr_working_range_assessment.csv');

writetable( ...
    workingRangeTable, ...
    csvFile);

%% =========================================================
% Save Tyre Contact CSV
% ==========================================================

tyreCSV = fullfile( ...
    resultsFolder, ...
    'lqr_tyre_contact_assessment.csv');

writetable( ...
    tyreContactTable, ...
    tyreCSV);

%% =========================================================
% Save MAT File
% ==========================================================

matFile = fullfile( ...
    resultsFolder, ...
    'lqr_working_range_assessment.mat');

save( ...
    matFile, ...
    'workingRangeTable', ...
    'tyreContactTable', ...
    'PeakSuspDeflection_mm', ...
    'PeakSuspVelocity_mps', ...
    'PeakTyreDeflection_mm', ...
    'PeakActuatorForce_N', ...
    'ActuatorUtilization_pct', ...
    'MinFz_N', ...
    'MaxFz_N', ...
    'ContactLoss_pct', ...
    'tyreContactResult', ...
    'deltaFL', ...
    'deltaFR', ...
    'deltaRL', ...
    'deltaRR', ...
    'deltaDotFL', ...
    'deltaDotFR', ...
    'deltaDotRL', ...
    'deltaDotRR', ...
    'tyreDefFL', ...
    'tyreDefFR', ...
    'tyreDefRL', ...
    'tyreDefRR', ...
    'Fz_FL', ...
    'Fz_FR', ...
    'Fz_RL', ...
    'Fz_RR', ...
    'zrFL', ...
    'zrFR', ...
    'zrRL', ...
    'zrRR', ...
    't', ...
    'V', ...
    'kerb_duration', ...
    'rear_delay');

%% =========================================================
% Save TXT Summary
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'lqr_working_range_assessment.txt');

fid = fopen(txtFile,'w');

if fid == -1
    error('Unable to open TXT results file for writing.');
end

fprintf( ...
    fid, ...
    'FINAL TUNED LQR - WORKING RANGE ASSESSMENT\n');

fprintf( ...
    fid, ...
    '==========================================\n\n');

fprintf( ...
    fid, ...
    'Operating condition = 144 km/h asymmetric kerb\n');

fprintf( ...
    fid, ...
    'Vehicle speed = %.2f m/s\n', ...
    V);

fprintf( ...
    fid, ...
    'Kerb height = %.4f m\n', ...
    kerb_height);

fprintf( ...
    fid, ...
    'Kerb duration = %.6f s\n', ...
    kerb_duration);

fprintf( ...
    fid, ...
    'Rear axle delay = %.6f s\n\n', ...
    rear_delay);

fprintf( ...
    fid, ...
    'WORKING RANGE RESULTS\n');

fprintf( ...
    fid, ...
    '------------------------------------------\n\n');

for i = 1:4

    fprintf( ...
        fid, ...
        '%s corner\n', ...
        cornerNames{i});

    fprintf( ...
        fid, ...
        'Peak suspension deflection = %.4f mm\n', ...
        PeakSuspDeflection_mm(i));

    fprintf( ...
        fid, ...
        'Peak suspension velocity = %.5f m/s\n', ...
        PeakSuspVelocity_mps(i));

    fprintf( ...
        fid, ...
        'Peak tyre deflection = %.4f mm\n', ...
        PeakTyreDeflection_mm(i));

    fprintf( ...
        fid, ...
        'Peak actuator force = %.2f N\n', ...
        PeakActuatorForce_N(i));

    fprintf( ...
        fid, ...
        'Actuator utilization = %.2f %%\n\n', ...
        ActuatorUtilization_pct(i));

end

fprintf( ...
    fid, ...
    '\nTYRE CONTACT RESULTS\n');

fprintf( ...
    fid, ...
    '------------------------------------------\n\n');

for i = 1:4

    fprintf( ...
        fid, ...
        '%s corner\n', ...
        cornerNames{i});

    fprintf( ...
        fid, ...
        'Minimum normal load = %.2f N\n', ...
        MinFz_N(i));

    fprintf( ...
        fid, ...
        'Maximum normal load = %.2f N\n', ...
        MaxFz_N(i));

    fprintf( ...
        fid, ...
        'Contact-loss duration = %.5f %%\n\n', ...
        ContactLoss_pct(i));

end

fprintf( ...
    fid, ...
    'Minimum normal load across vehicle = %.2f N\n', ...
    min(MinFz_N));

fprintf( ...
    fid, ...
    'Maximum contact-loss duration = %.5f %%\n', ...
    max(ContactLoss_pct));

fprintf( ...
    fid, ...
    'Tyre contact result = %s\n', ...
    tyreContactResult);

fclose(fid);

%% =========================================================
% Suspension Deflection Plot
% ==========================================================

fig1 = figure( ...
    'Name', ...
    'Suspension Working Range', ...
    'NumberTitle', ...
    'off');

plot( ...
    t, ...
    1000*deltaFL, ...
    'LineWidth', ...
    1.2);

hold on

plot( ...
    t, ...
    1000*deltaFR, ...
    'LineWidth', ...
    1.2);

plot( ...
    t, ...
    1000*deltaRL, ...
    'LineWidth', ...
    1.2);

plot( ...
    t, ...
    1000*deltaRR, ...
    'LineWidth', ...
    1.2);

grid on

xlabel('Time [s]')
ylabel('Suspension Deflection [mm]')

title( ...
    'Final LQR Suspension Deflection - 144 km/h Kerb');

legend( ...
    'FL', ...
    'FR', ...
    'RL', ...
    'RR', ...
    'Location', ...
    'best');

suspPNG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_suspension_deflection.png');

suspFIG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_suspension_deflection.fig');

exportgraphics( ...
    fig1, ...
    suspPNG, ...
    'Resolution', ...
    300);

savefig( ...
    fig1, ...
    suspFIG);

%% =========================================================
% Suspension Relative Velocity Plot
% ==========================================================

fig2 = figure( ...
    'Name', ...
    'Suspension Velocity', ...
    'NumberTitle', ...
    'off');

plot( ...
    t, ...
    deltaDotFL, ...
    'LineWidth', ...
    1.2);

hold on

plot( ...
    t, ...
    deltaDotFR, ...
    'LineWidth', ...
    1.2);

plot( ...
    t, ...
    deltaDotRL, ...
    'LineWidth', ...
    1.2);

plot( ...
    t, ...
    deltaDotRR, ...
    'LineWidth', ...
    1.2);

grid on

xlabel('Time [s]')
ylabel('Relative Suspension Velocity [m/s]')

title( ...
    'Final LQR Suspension Velocity - 144 km/h Kerb');

legend( ...
    'FL', ...
    'FR', ...
    'RL', ...
    'RR', ...
    'Location', ...
    'best');

velocityPNG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_suspension_velocity.png');

velocityFIG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_suspension_velocity.fig');

exportgraphics( ...
    fig2, ...
    velocityPNG, ...
    'Resolution', ...
    300);

savefig( ...
    fig2, ...
    velocityFIG);

%% =========================================================
% Actuator Utilization Plot
% ==========================================================

fig3 = figure( ...
    'Name', ...
    'Actuator Utilization', ...
    'NumberTitle', ...
    'off');

bar( ...
    categorical(cornerNames), ...
    ActuatorUtilization_pct);

hold on

yline( ...
    100, ...
    '--', ...
    'Actuator Limit');

grid on

xlabel('Corner')
ylabel('Actuator Utilization [%]')

title( ...
    'Peak Actuator Utilization - 144 km/h Kerb');

ylim([0 110]);

utilPNG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_actuator_utilization.png');

utilFIG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_actuator_utilization.fig');

exportgraphics( ...
    fig3, ...
    utilPNG, ...
    'Resolution', ...
    300);

savefig( ...
    fig3, ...
    utilFIG);

%% =========================================================
% Tyre Normal Load Plot
% ==========================================================

fig4 = figure( ...
    'Name', ...
    'Tyre Normal Loads', ...
    'NumberTitle', ...
    'off');

plot( ...
    t, ...
    Fz_FL, ...
    'LineWidth', ...
    1.2);

hold on

plot( ...
    t, ...
    Fz_FR, ...
    'LineWidth', ...
    1.2);

plot( ...
    t, ...
    Fz_RL, ...
    'LineWidth', ...
    1.2);

plot( ...
    t, ...
    Fz_RR, ...
    'LineWidth', ...
    1.2);

yline( ...
    0, ...
    '--', ...
    'Zero Normal Load');

grid on

xlabel('Time [s]')
ylabel('Tyre Normal Load [N]')

title( ...
    'Tyre Normal Loads - 144 km/h Asymmetric Kerb');

legend( ...
    'FL', ...
    'FR', ...
    'RL', ...
    'RR', ...
    'Zero Load', ...
    'Location', ...
    'best');

tyrePNG = fullfile( ...
    projectFolder, 'Plots', 'Final', ...
    'lqr_working_range_tyre_load.png');

tyreFIG = fullfile( ...
    projectFolder, 'Plots', 'Final', ...
    'lqr_working_range_tyre_load.fig');

exportgraphics( ...
    fig4, ...
    tyrePNG, ...
    'Resolution', ...
    300);

savefig( ...
    fig4, ...
    tyreFIG);

%% =========================================================
% Tyre Contact Loss Bar Plot
% ==========================================================

fig5 = figure( ...
    'Name', ...
    'Tyre Contact Loss', ...
    'NumberTitle', ...
    'off');

bar( ...
    categorical(cornerNames), ...
    ContactLoss_pct);

grid on

xlabel('Corner')
ylabel('Time at F_z <= 0 [%]')

title( ...
    'Predicted Tyre Contact Loss - 144 km/h Kerb');

contactPNG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_tyre_contact_loss.png');

contactFIG = fullfile( ...
    plotsFolder, ...
    'lqr_working_range_tyre_contact_loss.fig');

exportgraphics( ...
    fig5, ...
    contactPNG, ...
    'Resolution', ...
    300);

savefig( ...
    fig5, ...
    contactFIG);

%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('====================================================')
disp('WORKING-RANGE ASSESSMENT SAVED SUCCESSFULLY')
disp('====================================================')

fprintf('\nResults:\n');
fprintf('%s\n',txtFile);
fprintf('%s\n',csvFile);
fprintf('%s\n',tyreCSV);
fprintf('%s\n',matFile);

fprintf('\nPlots:\n');
fprintf('%s\n',suspPNG);
fprintf('%s\n',velocityPNG);
fprintf('%s\n',utilPNG);
fprintf('%s\n',tyrePNG);
fprintf('%s\n',contactPNG);

%% =========================================================
% Helper Function
% IMPORTANT:
% Local functions must remain at the END of this script.
% ==========================================================

function sig = getLoggedSignal(simOut,signalName)

    try

        sig = simOut.get(signalName);

        if ~isempty(sig)
            return;
        end

    catch
    end

    if evalin( ...
            'base', ...
            sprintf( ...
                'exist(''%s'',''var'')', ...
                signalName))

        sig = evalin( ...
            'base', ...
            signalName);

        return;

    end

    error( ...
        'Unable to locate logged signal: %s', ...
        signalName);

end
