%% Final Tuned LQR - Vehicle Speed Sensitivity
% Symmetric bump evaluated at increasing vehicle speeds

clc;

%% =========================================================
% Load Vehicle Parameters FIRST
% ==========================================================
%
% vehicle_parameters.m contains "clear", so it must run
% before this script creates its own local variables.

run(fullfile(fileparts(fileparts(fileparts(mfilename('fullpath')))), ...
    'Scripts', '01_Parameters', 'vehicle_parameters.m'));

%% =========================================================
% Project Paths
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
plotsFolder = fullfile(projectFolder, 'Plots', 'Operating_Envelope');

if ~exist(plotsFolder, 'dir')
    mkdir(plotsFolder);
end

%% =========================================================
% Load Final Tuned LQR Controller
% ==========================================================

controllerFile = fullfile( ...
    lqrResultsFolder, ...
    'final_tuned_lqr_controller.mat');

if ~isfile(controllerFile)
    error('final_tuned_lqr_controller.mat not found.');
end

controllerData = load(controllerFile);

K_lqr = controllerData.K_lqr_final;
final_lqr_ratio = controllerData.finalRatio;

fprintf('============================================\n');
fprintf('FINAL TUNED LQR CONTROLLER LOADED\n');
fprintf('============================================\n');
fprintf('K_lqr size = %d x %d\n', ...
    size(K_lqr,1), size(K_lqr,2));
fprintf('Final Q/R ratio = %.3f\n', ...
    final_lqr_ratio);
fprintf('============================================\n');

%% =========================================================
% Model
% ==========================================================

modelName = 'RaceCar_7DOF_ActiveSuspension';

load_system(fullfile( ...
    projectFolder, ...
    'Model', ...
    [modelName '.slx']));

%% =========================================================
% Test Speeds
% ==========================================================

V_test = [10 20 30 40];

nCases = length(V_test);

Speed_mps = zeros(nCases,1);
Speed_kph = zeros(nCases,1);

PeakHeave_mm = zeros(nCases,1);
PeakPitch_deg = zeros(nCases,1);

RMSHeaveAccel_mps2 = zeros(nCases,1);
RMSPitchAccel_degps2 = zeros(nCases,1);

SettlingTime_s = zeros(nCases,1);

PeakForce_N = zeros(nCases,1);
MeanRMSForce_N = zeros(nCases,1);

MaxSaturation_pct = zeros(nCases,1);

BumpDuration_s = zeros(nCases,1);
RearDelay_s = zeros(nCases,1);

%% =========================================================
% Test Loop
% ==========================================================

disp('====================================================')
disp('FINAL LQR - VEHICLE SPEED SENSITIVITY')
disp('====================================================')

for k = 1:nCases

    V_case = V_test(k);

    %% -----------------------------------------------------
    % Speed-dependent road parameters
    % ------------------------------------------------------

    bump_duration_case = ...
        bump_length / V_case;

    rear_delay_case = ...
        L / V_case;

    t_bump_rear_case = ...
        t_bump_front + rear_delay_case;

    assignin( ...
        'base', ...
        'V', ...
        V_case);

    assignin( ...
        'base', ...
        'bump_duration', ...
        bump_duration_case);

    assignin( ...
        'base', ...
        'rear_delay', ...
        rear_delay_case);

    assignin( ...
        'base', ...
        't_bump_rear', ...
        t_bump_rear_case);

    assignin( ...
        'base', ...
        'K_lqr', ...
        K_lqr);

    assignin( ...
        'base', ...
        'active_mode', ...
        1);

    assignin( ...
        'base', ...
        'F_act_max', ...
        3000);

    fprintf( ...
        '\nRunning V = %.1f m/s (%.0f km/h)\n', ...
        V_case, ...
        3.6*V_case);

    %% -----------------------------------------------------
    % Run
    % ------------------------------------------------------

    simOut = sim( ...
        modelName, ...
        'StopTime', ...
        '5', ...
        'ReturnWorkspaceOutputs', ...
        'on');

    %% -----------------------------------------------------
    % Signals
    % ------------------------------------------------------

    z_s_sig = getLoggedSignal( ...
        simOut, ...
        'z_s_out');

    theta_sig = getLoggedSignal( ...
        simOut, ...
        'theta_out');

    z_s_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'z_s_ddot_out');

    theta_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'theta_ddot_out');

    FL_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_FL_out');

    FR_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_FR_out');

    RL_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_RL_out');

    RR_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_RR_out');

    %% -----------------------------------------------------
    % Data
    % ------------------------------------------------------

    t = z_s_sig.Time;

    z_s = z_s_sig.Data;

    theta = ...
        rad2deg(theta_sig.Data);

    z_s_ddot = ...
        z_s_ddot_sig.Data;

    theta_ddot = ...
        rad2deg(theta_ddot_sig.Data);

    FL = FL_sig.Data;
    FR = FR_sig.Data;
    RL = RL_sig.Data;
    RR = RR_sig.Data;

    %% -----------------------------------------------------
    % Metrics
    % ------------------------------------------------------

    PeakHeave_mm(k) = ...
        1000 * max(abs(z_s));

    PeakPitch_deg(k) = ...
        max(abs(theta));

    RMSHeaveAccel_mps2(k) = ...
        rms(z_s_ddot);

    RMSPitchAccel_degps2(k) = ...
        rms(theta_ddot);

    %% Settling

    threshold = ...
        0.02 * max(abs(z_s));

    settlingTime = NaN;

    for i = 1:length(z_s)

        if t(i) >= t_bump_front

            if all( ...
                    abs(z_s(i:end)) <= threshold)

                settlingTime = t(i);
                break;

            end

        end

    end

    SettlingTime_s(k) = ...
        settlingTime;

    %% Actuator

    PeakForce_N(k) = max([ ...
        max(abs(FL)), ...
        max(abs(FR)), ...
        max(abs(RL)), ...
        max(abs(RR))]);

    MeanRMSForce_N(k) = mean([ ...
        rms(FL), ...
        rms(FR), ...
        rms(RL), ...
        rms(RR)]);

    MaxSaturation_pct(k) = max([ ...
        100*mean(abs(FL) >= 0.999*F_act_max), ...
        100*mean(abs(FR) >= 0.999*F_act_max), ...
        100*mean(abs(RL) >= 0.999*F_act_max), ...
        100*mean(abs(RR) >= 0.999*F_act_max)]);

    %% Store test setup

    Speed_mps(k) = ...
        V_case;

    Speed_kph(k) = ...
        3.6 * V_case;

    BumpDuration_s(k) = ...
        bump_duration_case;

    RearDelay_s(k) = ...
        rear_delay_case;

    fprintf( ...
        ['Peak heave = %.4f mm | ' ...
         'Peak pitch = %.5f deg | ' ...
         'Peak force = %.1f N\n'], ...
        PeakHeave_mm(k), ...
        PeakPitch_deg(k), ...
        PeakForce_N(k));

end

%% =========================================================
% Results Table
% ==========================================================

speedTable = table( ...
    Speed_mps, ...
    Speed_kph, ...
    BumpDuration_s, ...
    RearDelay_s, ...
    PeakHeave_mm, ...
    PeakPitch_deg, ...
    RMSHeaveAccel_mps2, ...
    RMSPitchAccel_degps2, ...
    SettlingTime_s, ...
    PeakForce_N, ...
    MeanRMSForce_N, ...
    MaxSaturation_pct);

disp(' ')
disp('====================================================')
disp('LQR SPEED SENSITIVITY RESULTS')
disp('====================================================')

disp(speedTable);

%% =========================================================
% Save Results
% ==========================================================

csvFile = fullfile( ...
    resultsFolder, ...
    'lqr_speed_sensitivity.csv');

writetable(speedTable, csvFile);

matFile = fullfile( ...
    resultsFolder, ...
    'lqr_speed_sensitivity.mat');

save(matFile, ...
    'speedTable', ...
    'V_test');

txtFile = fullfile( ...
    resultsFolder, ...
    'lqr_speed_sensitivity.txt');

fid = fopen(txtFile, 'w');

fprintf(fid, ...
    'FINAL TUNED LQR - SPEED SENSITIVITY\n');

fprintf(fid, ...
    '===================================\n\n');

for k = 1:nCases

    fprintf(fid, ...
        'Speed = %.1f m/s (%.1f km/h)\n', ...
        Speed_mps(k), ...
        Speed_kph(k));

    fprintf(fid, ...
        'Bump duration = %.6f s\n', ...
        BumpDuration_s(k));

    fprintf(fid, ...
        'Rear axle delay = %.6f s\n', ...
        RearDelay_s(k));

    fprintf(fid, ...
        'Peak heave = %.5f mm\n', ...
        PeakHeave_mm(k));

    fprintf(fid, ...
        'Peak pitch = %.6f deg\n', ...
        PeakPitch_deg(k));

    fprintf(fid, ...
        'RMS heave accel = %.6f m/s^2\n', ...
        RMSHeaveAccel_mps2(k));

    fprintf(fid, ...
        'RMS pitch accel = %.6f deg/s^2\n', ...
        RMSPitchAccel_degps2(k));

    fprintf(fid, ...
        'Settling time = %.5f s\n', ...
        SettlingTime_s(k));

    fprintf(fid, ...
        'Peak actuator force = %.2f N\n', ...
        PeakForce_N(k));

    fprintf(fid, ...
        'Mean RMS actuator force = %.2f N\n', ...
        MeanRMSForce_N(k));

    fprintf(fid, ...
        'Maximum saturation = %.4f %%\n\n', ...
        MaxSaturation_pct(k));

end

fclose(fid);

%% =========================================================
% Body Response Plot
% ==========================================================

fig1 = figure( ...
    'Name', ...
    'LQR Speed Sensitivity - Body Response', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

plot( ...
    Speed_kph, ...
    PeakHeave_mm, ...
    '-o', ...
    'LineWidth', ...
    1.5);

grid on

xlabel('Vehicle Speed [km/h]')
ylabel('Peak Heave [mm]')

title('Peak Heave vs Vehicle Speed');

subplot(2,1,2)

plot( ...
    Speed_kph, ...
    PeakPitch_deg, ...
    '-o', ...
    'LineWidth', ...
    1.5);

grid on

xlabel('Vehicle Speed [km/h]')
ylabel('Peak Pitch [deg]')

title('Peak Pitch vs Vehicle Speed');

bodyPNG = fullfile( ...
    plotsFolder, ...
    'lqr_speed_sensitivity_body_motion.png');

bodyFIG = fullfile( ...
    plotsFolder, ...
    'lqr_speed_sensitivity_body_motion.fig');

exportgraphics( ...
    fig1, ...
    bodyPNG, ...
    'Resolution', ...
    300);

savefig(fig1, bodyFIG);

%% =========================================================
% Acceleration Plot
% ==========================================================

fig2 = figure( ...
    'Name', ...
    'LQR Speed Sensitivity - Acceleration', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

plot( ...
    Speed_kph, ...
    RMSHeaveAccel_mps2, ...
    '-o', ...
    'LineWidth', ...
    1.5);

grid on

xlabel('Vehicle Speed [km/h]')
ylabel('RMS Heave Accel [m/s^2]')

title('RMS Heave Acceleration vs Vehicle Speed');

subplot(2,1,2)

plot( ...
    Speed_kph, ...
    RMSPitchAccel_degps2, ...
    '-o', ...
    'LineWidth', ...
    1.5);

grid on

xlabel('Vehicle Speed [km/h]')
ylabel('RMS Pitch Accel [deg/s^2]')

title('RMS Pitch Acceleration vs Vehicle Speed');

accelPNG = fullfile( ...
    plotsFolder, ...
    'lqr_speed_sensitivity_acceleration.png');

accelFIG = fullfile( ...
    plotsFolder, ...
    'lqr_speed_sensitivity_acceleration.fig');

exportgraphics( ...
    fig2, ...
    accelPNG, ...
    'Resolution', ...
    300);

savefig(fig2, accelFIG);

%% =========================================================
% Actuator Plot
% ==========================================================

fig3 = figure( ...
    'Name', ...
    'LQR Speed Sensitivity - Actuator Demand', ...
    'NumberTitle', ...
    'off');

plot( ...
    Speed_kph, ...
    PeakForce_N, ...
    '-o', ...
    'LineWidth', ...
    1.5);

hold on

yline( ...
    F_act_max, ...
    '--');

grid on

xlabel('Vehicle Speed [km/h]')
ylabel('Peak Actuator Force [N]')

title('Peak Actuator Force vs Vehicle Speed');

actuatorPNG = fullfile( ...
    plotsFolder, ...
    'lqr_speed_sensitivity_actuator.png');

actuatorFIG = fullfile( ...
    plotsFolder, ...
    'lqr_speed_sensitivity_actuator.fig');

exportgraphics( ...
    fig3, ...
    actuatorPNG, ...
    'Resolution', ...
    300);

savefig(fig3, actuatorFIG);

%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('LQR speed sensitivity saved successfully.');

fprintf('\nResults:\n');
fprintf('%s\n', txtFile);
fprintf('%s\n', csvFile);
fprintf('%s\n', matFile);

fprintf('\nPlots:\n');
fprintf('%s\n', bodyPNG);
fprintf('%s\n', accelPNG);
fprintf('%s\n', actuatorPNG);

%% =========================================================
% Helper
% ==========================================================

function sig = getLoggedSignal(simOut, signalName)

    try

        sig = simOut.get(signalName);

        if ~isempty(sig)
            return;
        end

    catch
    end

    if evalin( ...
            'base', ...
            sprintf( ...
                'exist(''%s'',''var'')', ...
                signalName))

        sig = evalin( ...
            'base', ...
            signalName);

        return;

    end

    error( ...
        'Unable to locate logged signal: %s', ...
        signalName);

end
