%% Motorsport Operating-Condition Conclusions
% Consolidates final operating-envelope findings
% from the tuned LQR investigation.

clear;
clc;

%% =========================================================
% Project Paths
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
plotsFolder = fullfile(projectFolder, 'Plots', 'Operating_Envelope');

if ~exist(plotsFolder,'dir')
    mkdir(plotsFolder);
end

%% =========================================================
% Load Saved Results
% ==========================================================

speedData = load(fullfile( ...
    resultsFolder, ...
    'lqr_speed_sensitivity.mat'));

kerbData = load(fullfile( ...
    resultsFolder, ...
    'lqr_high_speed_kerb.mat'));

workingData = load(fullfile( ...
    resultsFolder, ...
    'lqr_working_range_assessment.mat'));

%% =========================================================
% Working Range Results
% ==========================================================

workingTable = ...
    workingData.workingRangeTable;

contactTable = ...
    workingData.tyreContactTable;

maxSuspDeflection = ...
    max(workingTable.PeakSuspDeflection_mm);

maxSuspVelocity = ...
    max(workingTable.PeakSuspVelocity_mps);

maxTyreDeflection = ...
    max(workingTable.PeakTyreDeflection_mm);

maxActuatorForce = ...
    max(workingTable.PeakActuatorForce_N);

maxActuatorUtilization = ...
    max(workingTable.ActuatorUtilization_pct);

minNormalLoad = ...
    min(contactTable.MinimumNormalLoad_N);

maxContactLoss = ...
    max(contactTable.ContactLoss_pct);

%% =========================================================
% High-Speed Kerb Comparison
% ==========================================================

kerbTable = ...
    kerbData.kerbSpeedTable;

lowIdx = 1;
highIdx = height(kerbTable);

heaveReduction = ...
    100 * ...
    (1 - ...
    kerbTable.PeakHeave_mm(highIdx) / ...
    kerbTable.PeakHeave_mm(lowIdx));

pitchReduction = ...
    100 * ...
    (1 - ...
    kerbTable.PeakPitch_deg(highIdx) / ...
    kerbTable.PeakPitch_deg(lowIdx));

rollReduction = ...
    100 * ...
    (1 - ...
    kerbTable.PeakRoll_deg(highIdx) / ...
    kerbTable.PeakRoll_deg(lowIdx));

actuatorReduction = ...
    100 * ...
    (1 - ...
    kerbTable.PeakForce_N(highIdx) / ...
    kerbTable.PeakForce_N(lowIdx));

%% =========================================================
% Summary Structure
% ==========================================================

motorsportSummary.MaxSuspensionDeflection_mm = ...
    maxSuspDeflection;

motorsportSummary.MaxSuspensionVelocity_mps = ...
    maxSuspVelocity;

motorsportSummary.MaxTyreDeflection_mm = ...
    maxTyreDeflection;

motorsportSummary.MaxActuatorForce_N = ...
    maxActuatorForce;

motorsportSummary.MaxActuatorUtilization_pct = ...
    maxActuatorUtilization;

motorsportSummary.MinimumPredictedNormalLoad_N = ...
    minNormalLoad;

motorsportSummary.MaximumContactLoss_pct = ...
    maxContactLoss;

motorsportSummary.HighSpeedHeaveReduction_pct = ...
    heaveReduction;

motorsportSummary.HighSpeedPitchReduction_pct = ...
    pitchReduction;

motorsportSummary.HighSpeedRollReduction_pct = ...
    rollReduction;

motorsportSummary.HighSpeedActuatorReduction_pct = ...
    actuatorReduction;

%% =========================================================
% Display
% ==========================================================

disp('====================================================')
disp('MOTORSPORT OPERATING-CONDITION CONCLUSIONS')
disp('====================================================')

fprintf( ...
    'Maximum suspension deflection = %.3f mm\n', ...
    maxSuspDeflection);

fprintf( ...
    'Maximum suspension velocity   = %.3f m/s\n', ...
    maxSuspVelocity);

fprintf( ...
    'Maximum tyre deflection       = %.3f mm\n', ...
    maxTyreDeflection);

fprintf( ...
    'Maximum actuator force        = %.2f N\n', ...
    maxActuatorForce);

fprintf( ...
    'Maximum actuator utilization  = %.2f %%\n', ...
    maxActuatorUtilization);

fprintf( ...
    'Minimum predicted tyre load   = %.2f N\n', ...
    minNormalLoad);

fprintf( ...
    'Maximum contact-loss fraction = %.4f %%\n', ...
    maxContactLoss);

disp(' ')
disp('72 -> 144 km/h KERB RESPONSE CHANGE')

fprintf( ...
    'Peak heave reduction    = %.2f %%\n', ...
    heaveReduction);

fprintf( ...
    'Peak pitch reduction    = %.2f %%\n', ...
    pitchReduction);

fprintf( ...
    'Peak roll reduction     = %.2f %%\n', ...
    rollReduction);

fprintf( ...
    'Actuator-force reduction = %.2f %%\n', ...
    actuatorReduction);

%% =========================================================
% Save TXT Conclusions
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'motorsport_operating_conclusions.txt');

fid = fopen(txtFile,'w');

fprintf(fid, ...
    'MOTORSPORT OPERATING-CONDITION CONCLUSIONS\n');

fprintf(fid, ...
    '==========================================\n\n');

fprintf(fid, ...
    ['The final tuned LQR controller remained well within ' ...
     'the defined 3000 N actuator-force limit throughout ' ...
     'the evaluated operating conditions.\n\n']);

fprintf(fid, ...
    ['At the 144 km/h asymmetric kerb condition, maximum ' ...
     'actuator utilization was %.2f %%, with a peak ' ...
     'suspension deflection of %.3f mm and peak relative ' ...
     'suspension velocity of %.3f m/s.\n\n'], ...
    maxActuatorUtilization, ...
    maxSuspDeflection, ...
    maxSuspVelocity);

fprintf(fid, ...
    ['Increasing vehicle speed from 72 km/h to 144 km/h ' ...
     'for the fixed-length kerb reduced peak heave by ' ...
     '%.2f %%, peak pitch by %.2f %%, peak roll by ' ...
     '%.2f %% and peak actuator force by %.2f %%.\n\n'], ...
    heaveReduction, ...
    pitchReduction, ...
    rollReduction, ...
    actuatorReduction);

fprintf(fid, ...
    ['This reduction in sprung-mass response should not ' ...
     'be interpreted as the high-speed kerb being less ' ...
     'mechanically severe. The shorter road-input duration ' ...
     'produced high suspension velocities and strong ' ...
     'wheel-level transient behaviour.\n\n']);

fprintf(fid, ...
    ['The linear tyre model predicted a minimum normal ' ...
     'load of %.2f N and temporary unloading for up to ' ...
     '%.4f %% of the simulation. Negative predicted tyre ' ...
     'loads are non-physical and indicate that the linear ' ...
     'tyre model has exceeded its valid operating region.\n\n'], ...
    minNormalLoad, ...
    maxContactLoss);

fprintf(fid, ...
    ['For future high-fidelity kerb-impact analysis, the ' ...
     'model should therefore be extended with unilateral ' ...
     'tyre contact, nonlinear tyre stiffness and potentially ' ...
     'nonlinear damper behaviour.\n\n']);

fprintf(fid, ...
    ['Within the valid linear operating region, the tuned ' ...
     'LQR controller demonstrates effective control of ' ...
     'sprung-mass motion while requiring substantially less ' ...
     'than the available actuator-force capability.\n']);

fclose(fid);

%% =========================================================
% Save MAT
% ==========================================================

matFile = fullfile( ...
    resultsFolder, ...
    'motorsport_operating_conclusions.mat');

save( ...
    matFile, ...
    'motorsportSummary');

%% =========================================================
% Final Summary Plot
% ==========================================================

metrics = [ ...
    maxActuatorUtilization, ...
    maxContactLoss];

fig1 = figure( ...
    'Name', ...
    'Motorsport Operating Envelope', ...
    'NumberTitle', ...
    'off');

yyaxis left

bar(1,maxActuatorUtilization);

ylabel('Actuator Utilization [%]')
ylim([0 100])

yyaxis right

bar(2,maxContactLoss);

ylabel('Predicted Contact-Loss Time [%]')

xticks([1 2])

xticklabels({ ...
    'Peak Actuator Utilization', ...
    'Tyre Contact Loss'});

grid on

title('Final LQR Motorsport Operating-Envelope Indicators');

plotPNG = fullfile( ...
    plotsFolder, ...
    'motorsport_operating_envelope_summary.png');

plotFIG = fullfile( ...
    plotsFolder, ...
    'motorsport_operating_envelope_summary.fig');

exportgraphics( ...
    fig1, ...
    plotPNG, ...
    'Resolution',300);

savefig(fig1,plotFIG);

%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('Motorsport operating conclusions saved successfully.')

fprintf('\nResults:\n');
fprintf('%s\n',txtFile);
fprintf('%s\n',matFile);

fprintf('\nPlot:\n');
fprintf('%s\n',plotPNG);