%% Final Validation Summary
% Step 11D
%
% Consolidates:
% 1. Passive baseline
% 2. Optimized Skyhook
% 3. Final tuned LQR
% 4. Controller robustness
% 5. Closed-loop stability
% 6. High-speed kerb / operating-envelope results
%
% All results and plots are saved automatically.

clear;
clc;
close all;

%% =========================================================
% Project Paths
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Final');
plotsFolder = fullfile(projectFolder, 'Plots', 'Final');

if ~exist(plotsFolder,'dir')
    mkdir(plotsFolder);
end

%% =========================================================
% Required Files
% ==========================================================

passiveFile = fullfile( ...
    passiveResultsFolder, ...
    'passive_baseline_summary.mat');

skyhookFile = fullfile( ...
    skyhookResultsFolder, ...
    'optimized_skyhook_summary.mat');

lqrBenchmarkFile = fullfile( ...
    resultsFolder, ...
    'final_controller_benchmark.mat');

robustnessFile = fullfile( ...
    robustnessResultsFolder, ...
    'controller_robustness_comparison.mat');

stabilityFile = fullfile( ...
    lqrResultsFolder, ...
    'final_lqr_stability_verification.mat');

highSpeedKerbFile = fullfile( ...
    operatingResultsFolder, ...
    'lqr_high_speed_kerb.mat');

workingRangeFile = fullfile( ...
    operatingResultsFolder, ...
    'lqr_working_range_assessment.mat');

%% =========================================================
% Check Files Exist
% ==========================================================

requiredFiles = { ...
    passiveFile, ...
    skyhookFile, ...
    lqrBenchmarkFile, ...
    robustnessFile, ...
    stabilityFile, ...
    highSpeedKerbFile, ...
    workingRangeFile};

for i = 1:numel(requiredFiles)

    if ~isfile(requiredFiles{i})

        error( ...
            'Required result file not found:\n%s', ...
            requiredFiles{i});

    end

end

%% =========================================================
% Load Results
% ==========================================================

passiveData = load(passiveFile);
skyhookData = load(skyhookFile);
benchmarkData = load(lqrBenchmarkFile);
robustnessData = load(robustnessFile);
stabilityData = load(stabilityFile);
highSpeedData = load(highSpeedKerbFile);
workingRangeData = load(workingRangeFile);

%% =========================================================
% Automatically Find Benchmark Tables
% ==========================================================

benchmarkFields = fieldnames(benchmarkData);

bumpTable = [];
kerbTable = [];

for i = 1:numel(benchmarkFields)

    candidate = benchmarkData.(benchmarkFields{i});

    if ~istable(candidate)
        continue
    end

    variableNames = candidate.Properties.VariableNames;

    %% -----------------------------------------------------
    % Symmetric Bump Table Detection
    % ------------------------------------------------------

    requiredBumpColumns = { ...
        'Controller', ...
        'PeakHeave_mm', ...
        'PeakPitch_deg', ...
        'RMSHeaveAccel', ...
        'RMSPitchAccel', ...
        'SettlingTime', ...
        'PeakForce'};

    if all(ismember(requiredBumpColumns, variableNames))

        bumpTable = candidate;

        fprintf( ...
            'Detected bump benchmark table: %s\n', ...
            benchmarkFields{i});

    end

    %% -----------------------------------------------------
    % Asymmetric Kerb Table Detection
    % ------------------------------------------------------

    requiredKerbColumns = { ...
        'Controller', ...
        'KerbPeakHeave_mm', ...
        'KerbPeakPitch_deg', ...
        'KerbPeakRoll_deg', ...
        'KerbRMSRollAccel', ...
        'KerbRollSettling', ...
        'KerbPeakForce'};

    if all(ismember(requiredKerbColumns, variableNames))

        kerbTable = candidate;

        fprintf( ...
            'Detected kerb benchmark table: %s\n', ...
            benchmarkFields{i});

    end

end

%% =========================================================
% Validate Detection
% ==========================================================

if isempty(bumpTable)

    disp(' ')
    disp('Variables found inside final_controller_benchmark.mat:')

    disp(benchmarkFields)

    error([ ...
        'Could not automatically locate the symmetric-bump ' ...
        'benchmark table.']);

end

if isempty(kerbTable)

    disp(' ')
    disp('Variables found inside final_controller_benchmark.mat:')

    disp(benchmarkFields)

    error([ ...
        'Could not automatically locate the asymmetric-kerb ' ...
        'benchmark table.']);

end

disp(' ')
disp('Benchmark tables detected successfully.')

%% =========================================================
% Controller Row Identification
% ==========================================================

controllerNames = string(bumpTable.Controller);

idxPassive = find(contains(controllerNames,'Passive'),1);
idxSkyhook = find(contains(controllerNames,'Skyhook'),1);
idxLQR = find(contains(controllerNames,'LQR'),1);

if isempty(idxPassive) || isempty(idxSkyhook) || isempty(idxLQR)

    error('Could not identify Passive, Skyhook and LQR rows.');

end

%% =========================================================
% Symmetric Bump Metrics
% ==========================================================

passivePeakHeave = bumpTable.PeakHeave_mm(idxPassive);
skyhookPeakHeave = bumpTable.PeakHeave_mm(idxSkyhook);
lqrPeakHeave = bumpTable.PeakHeave_mm(idxLQR);

passivePeakPitch = bumpTable.PeakPitch_deg(idxPassive);
skyhookPeakPitch = bumpTable.PeakPitch_deg(idxSkyhook);
lqrPeakPitch = bumpTable.PeakPitch_deg(idxLQR);

passiveRMSHeave = bumpTable.RMSHeaveAccel(idxPassive);
skyhookRMSHeave = bumpTable.RMSHeaveAccel(idxSkyhook);
lqrRMSHeave = bumpTable.RMSHeaveAccel(idxLQR);

passiveRMSPitch = bumpTable.RMSPitchAccel(idxPassive);
skyhookRMSPitch = bumpTable.RMSPitchAccel(idxSkyhook);
lqrRMSPitch = bumpTable.RMSPitchAccel(idxLQR);

passiveSettling = bumpTable.SettlingTime(idxPassive);
skyhookSettling = bumpTable.SettlingTime(idxSkyhook);
lqrSettling = bumpTable.SettlingTime(idxLQR);

passivePeakForce = bumpTable.PeakForce(idxPassive);
skyhookPeakForce = bumpTable.PeakForce(idxSkyhook);
lqrPeakForce = bumpTable.PeakForce(idxLQR);

%% =========================================================
% Asymmetric Kerb Metrics
% ==========================================================

kerbControllerNames = string(kerbTable.Controller);

idxPassiveKerb = find(contains(kerbControllerNames,'Passive'),1);
idxSkyhookKerb = find(contains(kerbControllerNames,'Skyhook'),1);
idxLQRKerb = find(contains(kerbControllerNames,'LQR'),1);

passiveKerbHeave = kerbTable.KerbPeakHeave_mm(idxPassiveKerb);
skyhookKerbHeave = kerbTable.KerbPeakHeave_mm(idxSkyhookKerb);
lqrKerbHeave = kerbTable.KerbPeakHeave_mm(idxLQRKerb);

passiveKerbPitch = kerbTable.KerbPeakPitch_deg(idxPassiveKerb);
skyhookKerbPitch = kerbTable.KerbPeakPitch_deg(idxSkyhookKerb);
lqrKerbPitch = kerbTable.KerbPeakPitch_deg(idxLQRKerb);

passiveKerbRoll = kerbTable.KerbPeakRoll_deg(idxPassiveKerb);
skyhookKerbRoll = kerbTable.KerbPeakRoll_deg(idxSkyhookKerb);
lqrKerbRoll = kerbTable.KerbPeakRoll_deg(idxLQRKerb);

passiveKerbRMSRoll = kerbTable.KerbRMSRollAccel(idxPassiveKerb);
skyhookKerbRMSRoll = kerbTable.KerbRMSRollAccel(idxSkyhookKerb);
lqrKerbRMSRoll = kerbTable.KerbRMSRollAccel(idxLQRKerb);

passiveKerbSettling = kerbTable.KerbRollSettling(idxPassiveKerb);
skyhookKerbSettling = kerbTable.KerbRollSettling(idxSkyhookKerb);
lqrKerbSettling = kerbTable.KerbRollSettling(idxLQRKerb);

passiveKerbForce = kerbTable.KerbPeakForce(idxPassiveKerb);
skyhookKerbForce = kerbTable.KerbPeakForce(idxSkyhookKerb);
lqrKerbForce = kerbTable.KerbPeakForce(idxLQRKerb);

%% =========================================================
% Improvement Calculations
% ==========================================================

improvement = @(passive,active) ...
    100*(passive-active)/passive;

lqrBumpHeaveImprove = improvement( ...
    passivePeakHeave, ...
    lqrPeakHeave);

lqrBumpPitchImprove = improvement( ...
    passivePeakPitch, ...
    lqrPeakPitch);

lqrBumpSettlingImprove = improvement( ...
    passiveSettling, ...
    lqrSettling);

skyBumpHeaveImprove = improvement( ...
    passivePeakHeave, ...
    skyhookPeakHeave);

skyBumpPitchImprove = improvement( ...
    passivePeakPitch, ...
    skyhookPeakPitch);

lqrKerbHeaveImprove = improvement( ...
    passiveKerbHeave, ...
    lqrKerbHeave);

lqrKerbPitchImprove = improvement( ...
    passiveKerbPitch, ...
    lqrKerbPitch);

lqrKerbRollImprove = improvement( ...
    passiveKerbRoll, ...
    lqrKerbRoll);

lqrKerbSettlingImprove = improvement( ...
    passiveKerbSettling, ...
    lqrKerbSettling);

skyKerbRollImprove = improvement( ...
    passiveKerbRoll, ...
    skyhookKerbRoll);

%% =========================================================
% Automatically Find Robustness Summary Table
% ==========================================================

robustnessFields = fieldnames(robustnessData);

robustnessSummary = [];

for i = 1:numel(robustnessFields)

    candidate = robustnessData.(robustnessFields{i});

    if ~istable(candidate)
        continue
    end

    variableNames = candidate.Properties.VariableNames;

    requiredRobustnessColumns = { ...
        'Controller', ...
        'MeanAbsSensitivity_pct', ...
        'AllCasesStable', ...
        'WorstPeakForce_N', ...
        'WorstSaturation_pct'};

    if all(ismember(requiredRobustnessColumns, variableNames))

        robustnessSummary = candidate;

        fprintf( ...
            'Detected robustness summary table: %s\n', ...
            robustnessFields{i});

        break

    end

end

%% =========================================================
% Validate Robustness Table Detection
% ==========================================================

if isempty(robustnessSummary)

    disp(' ')
    disp('Variables found inside controller_robustness_comparison.mat:')

    disp(robustnessFields)

    disp(' ')
    disp('Table variables and their columns:')

    for i = 1:numel(robustnessFields)

        candidate = robustnessData.(robustnessFields{i});

        if istable(candidate)

            fprintf('\nTable: %s\n', robustnessFields{i});
            disp(candidate.Properties.VariableNames)

        end

    end

    error([ ...
        'Could not automatically locate the controller ' ...
        'robustness summary table.']);

end

disp('Robustness summary table detected successfully.')

robustControllerNames = string(robustnessSummary.Controller);

idxRobLQR = find(contains(robustControllerNames,'LQR'),1);
idxRobSky = find(contains(robustControllerNames,'Skyhook'),1);

if isempty(idxRobLQR)
    error('Final Tuned LQR row not found in robustness summary table.');
end

if isempty(idxRobSky)
    error('Optimized Skyhook row not found in robustness summary table.');
end

lqrSensitivity = ...
    robustnessSummary.MeanAbsSensitivity_pct(idxRobLQR);

skySensitivity = ...
    robustnessSummary.MeanAbsSensitivity_pct(idxRobSky);

lqrWorstForce = ...
    robustnessSummary.WorstPeakForce_N(idxRobLQR);

skyWorstForce = ...
    robustnessSummary.WorstPeakForce_N(idxRobSky);

%% =========================================================
% Stability Summary
% ==========================================================

nominalStabilityMargin = ...
    stabilityData.stabilityMargin;

worstCaseStabilityMargin = ...
    stabilityData.worstMargin;

allCasesStable = ...
    stabilityData.allCasesStable;

%% =========================================================
% High-Speed Kerb Summary
% ==========================================================

if isfield(highSpeedData,'highSpeedTable')

    highSpeedTable = highSpeedData.highSpeedTable;

else

    % Try common alternative name
    fieldsHS = fieldnames(highSpeedData);

    tableFound = false;

    for i = 1:numel(fieldsHS)

        candidate = highSpeedData.(fieldsHS{i});

        if istable(candidate)

            highSpeedTable = candidate;
            tableFound = true;
            break

        end

    end

    if ~tableFound
        error('No high-speed kerb result table found.');
    end

end

%% =========================================================
% Working Range Summary
% ==========================================================

if isfield(workingRangeData,'workingRangeTable')

    workingRangeTable = ...
        workingRangeData.workingRangeTable;

else

    error('workingRangeTable not found in working-range MAT file.');

end

maxSuspDeflection = ...
    max(workingRangeTable.PeakSuspDeflection_mm);

maxSuspVelocity = ...
    max(workingRangeTable.PeakSuspVelocity_mps);

maxTyreDeflection = ...
    max(workingRangeTable.PeakTyreDeflection_mm);

maxActuatorUtilization = ...
    max(workingRangeTable.ActuatorUtilization_pct);

%% =========================================================
% Tyre Contact Information
% ==========================================================

if isfield(workingRangeData,'tyreContactTable')

    tyreContactTable = ...
        workingRangeData.tyreContactTable;

    minTyreLoad = ...
        min(tyreContactTable.MinimumNormalLoad_N);

    maxContactLoss = ...
        max(tyreContactTable.ContactLoss_pct);

else

    minTyreLoad = NaN;
    maxContactLoss = NaN;

end

%% =========================================================
% Final Consolidated Summary Table
% ==========================================================

Metric = { ...
    'Bump Peak Heave [mm]'; ...
    'Bump Peak Pitch [deg]'; ...
    'Bump RMS Heave Accel [m/s^2]'; ...
    'Bump RMS Pitch Accel [deg/s^2]'; ...
    'Bump Settling Time [s]'; ...
    'Bump Peak Actuator Force [N]'; ...
    'Kerb Peak Heave [mm]'; ...
    'Kerb Peak Pitch [deg]'; ...
    'Kerb Peak Roll [deg]'; ...
    'Kerb RMS Roll Accel [deg/s^2]'; ...
    'Kerb Roll Settling [s]'; ...
    'Kerb Peak Actuator Force [N]'};

Passive = [ ...
    passivePeakHeave; ...
    passivePeakPitch; ...
    passiveRMSHeave; ...
    passiveRMSPitch; ...
    passiveSettling; ...
    passivePeakForce; ...
    passiveKerbHeave; ...
    passiveKerbPitch; ...
    passiveKerbRoll; ...
    passiveKerbRMSRoll; ...
    passiveKerbSettling; ...
    passiveKerbForce];

OptimizedSkyhook = [ ...
    skyhookPeakHeave; ...
    skyhookPeakPitch; ...
    skyhookRMSHeave; ...
    skyhookRMSPitch; ...
    skyhookSettling; ...
    skyhookPeakForce; ...
    skyhookKerbHeave; ...
    skyhookKerbPitch; ...
    skyhookKerbRoll; ...
    skyhookKerbRMSRoll; ...
    skyhookKerbSettling; ...
    skyhookKerbForce];

FinalTunedLQR = [ ...
    lqrPeakHeave; ...
    lqrPeakPitch; ...
    lqrRMSHeave; ...
    lqrRMSPitch; ...
    lqrSettling; ...
    lqrPeakForce; ...
    lqrKerbHeave; ...
    lqrKerbPitch; ...
    lqrKerbRoll; ...
    lqrKerbRMSRoll; ...
    lqrKerbSettling; ...
    lqrKerbForce];

summaryTable = table( ...
    Metric, ...
    Passive, ...
    OptimizedSkyhook, ...
    FinalTunedLQR);

%% =========================================================
% Final Validation Indicators
% ==========================================================

Indicator = { ...
    'LQR Mean Parameter Sensitivity [%]'; ...
    'Skyhook Mean Parameter Sensitivity [%]'; ...
    'LQR Worst Robustness Peak Force [N]'; ...
    'Skyhook Worst Robustness Peak Force [N]'; ...
    'Nominal LQR Stability Margin [1/s]'; ...
    'Worst-Case LQR Stability Margin [1/s]'; ...
    'Maximum Suspension Deflection [mm]'; ...
    'Maximum Suspension Velocity [m/s]'; ...
    'Maximum Tyre Deflection [mm]'; ...
    'Maximum Actuator Utilization [%]'; ...
    'Minimum Predicted Tyre Load [N]'; ...
    'Maximum Predicted Contact-Loss Time [%]'};

Value = [ ...
    lqrSensitivity; ...
    skySensitivity; ...
    lqrWorstForce; ...
    skyWorstForce; ...
    nominalStabilityMargin; ...
    worstCaseStabilityMargin; ...
    maxSuspDeflection; ...
    maxSuspVelocity; ...
    maxTyreDeflection; ...
    maxActuatorUtilization; ...
    minTyreLoad; ...
    maxContactLoss];

indicatorTable = table( ...
    Indicator, ...
    Value);

%% =========================================================
% Console Summary
% ==========================================================

disp('====================================================')
disp('FINAL PROJECT VALIDATION SUMMARY')
disp('====================================================')

disp(' ')
disp('CONTROLLER BENCHMARK')
disp(summaryTable)

disp(' ')
disp('FINAL VALIDATION INDICATORS')
disp(indicatorTable)

fprintf('\nKEY LQR IMPROVEMENTS VS PASSIVE\n');
fprintf('Bump peak heave reduction    = %.2f %%\n', ...
    lqrBumpHeaveImprove);
fprintf('Bump peak pitch reduction    = %.2f %%\n', ...
    lqrBumpPitchImprove);
fprintf('Bump settling improvement    = %.2f %%\n', ...
    lqrBumpSettlingImprove);

fprintf('Kerb peak heave reduction    = %.2f %%\n', ...
    lqrKerbHeaveImprove);
fprintf('Kerb peak pitch reduction    = %.2f %%\n', ...
    lqrKerbPitchImprove);
fprintf('Kerb peak roll reduction     = %.2f %%\n', ...
    lqrKerbRollImprove);
fprintf('Kerb roll settling improve   = %.2f %%\n', ...
    lqrKerbSettlingImprove);

fprintf('\nROBUSTNESS\n');
fprintf('LQR mean sensitivity         = %.3f %%\n', ...
    lqrSensitivity);
fprintf('Skyhook mean sensitivity     = %.3f %%\n', ...
    skySensitivity);

fprintf('\nSTABILITY\n');
fprintf('Nominal LQR stability margin = %.3f 1/s\n', ...
    nominalStabilityMargin);
fprintf('Worst-case stability margin  = %.3f 1/s\n', ...
    worstCaseStabilityMargin);

if allCasesStable
    fprintf('All tested closed-loop cases = STABLE\n');
else
    fprintf('WARNING: At least one tested case was unstable.\n');
end

%% =========================================================
% Save Summary CSV
% ==========================================================

summaryCSV = fullfile( ...
    resultsFolder, ...
    'final_validation_controller_summary.csv');

writetable( ...
    summaryTable, ...
    summaryCSV);

indicatorCSV = fullfile( ...
    resultsFolder, ...
    'final_validation_indicators.csv');

writetable( ...
    indicatorTable, ...
    indicatorCSV);

%% =========================================================
% Save MAT
% ==========================================================

matFile = fullfile( ...
    resultsFolder, ...
    'final_validation_summary.mat');

save( ...
    matFile, ...
    'summaryTable', ...
    'indicatorTable', ...
    'lqrBumpHeaveImprove', ...
    'lqrBumpPitchImprove', ...
    'lqrBumpSettlingImprove', ...
    'lqrKerbHeaveImprove', ...
    'lqrKerbPitchImprove', ...
    'lqrKerbRollImprove', ...
    'lqrKerbSettlingImprove', ...
    'lqrSensitivity', ...
    'skySensitivity', ...
    'nominalStabilityMargin', ...
    'worstCaseStabilityMargin', ...
    'allCasesStable', ...
    'maxSuspDeflection', ...
    'maxSuspVelocity', ...
    'maxTyreDeflection', ...
    'maxActuatorUtilization', ...
    'minTyreLoad', ...
    'maxContactLoss');

%% =========================================================
% Save TXT Report
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'final_validation_summary.txt');

fid = fopen(txtFile,'w');

if fid == -1
    error('Unable to create final validation TXT file.');
end

fprintf(fid, ...
    'FINAL VALIDATION SUMMARY\n');

fprintf(fid, ...
    '==================================================\n\n');

fprintf(fid, ...
    'FINAL TUNED LQR - SYMMETRIC BUMP\n');

fprintf(fid, ...
    'Peak heave              = %.4f mm\n', ...
    lqrPeakHeave);

fprintf(fid, ...
    'Peak pitch              = %.5f deg\n', ...
    lqrPeakPitch);

fprintf(fid, ...
    'RMS heave acceleration  = %.5f m/s^2\n', ...
    lqrRMSHeave);

fprintf(fid, ...
    'RMS pitch acceleration  = %.5f deg/s^2\n', ...
    lqrRMSPitch);

fprintf(fid, ...
    'Settling time           = %.4f s\n', ...
    lqrSettling);

fprintf(fid, ...
    'Peak actuator force     = %.2f N\n\n', ...
    lqrPeakForce);

fprintf(fid, ...
    'FINAL TUNED LQR - ASYMMETRIC KERB\n');

fprintf(fid, ...
    'Peak heave              = %.4f mm\n', ...
    lqrKerbHeave);

fprintf(fid, ...
    'Peak pitch              = %.5f deg\n', ...
    lqrKerbPitch);

fprintf(fid, ...
    'Peak roll               = %.5f deg\n', ...
    lqrKerbRoll);

fprintf(fid, ...
    'RMS roll acceleration   = %.5f deg/s^2\n', ...
    lqrKerbRMSRoll);

fprintf(fid, ...
    'Roll settling time      = %.4f s\n', ...
    lqrKerbSettling);

fprintf(fid, ...
    'Peak actuator force     = %.2f N\n\n', ...
    lqrKerbForce);

fprintf(fid, ...
    'IMPROVEMENT VS PASSIVE\n');

fprintf(fid, ...
    'Bump peak heave reduction   = %.2f %%\n', ...
    lqrBumpHeaveImprove);

fprintf(fid, ...
    'Bump peak pitch reduction   = %.2f %%\n', ...
    lqrBumpPitchImprove);

fprintf(fid, ...
    'Bump settling improvement   = %.2f %%\n', ...
    lqrBumpSettlingImprove);

fprintf(fid, ...
    'Kerb peak heave reduction   = %.2f %%\n', ...
    lqrKerbHeaveImprove);

fprintf(fid, ...
    'Kerb peak pitch reduction   = %.2f %%\n', ...
    lqrKerbPitchImprove);

fprintf(fid, ...
    'Kerb peak roll reduction    = %.2f %%\n', ...
    lqrKerbRollImprove);

fprintf(fid, ...
    'Kerb roll settling improve  = %.2f %%\n\n', ...
    lqrKerbSettlingImprove);

fprintf(fid, ...
    'ROBUSTNESS\n');

fprintf(fid, ...
    'LQR mean sensitivity        = %.3f %%\n', ...
    lqrSensitivity);

fprintf(fid, ...
    'Skyhook mean sensitivity    = %.3f %%\n', ...
    skySensitivity);

fprintf(fid, ...
    'LQR worst robustness force  = %.2f N\n', ...
    lqrWorstForce);

fprintf(fid, ...
    'Skyhook worst robustness force = %.2f N\n\n', ...
    skyWorstForce);

fprintf(fid, ...
    'STABILITY\n');

fprintf(fid, ...
    'Nominal LQR margin          = %.5f 1/s\n', ...
    nominalStabilityMargin);

fprintf(fid, ...
    'Worst-case LQR margin       = %.5f 1/s\n', ...
    worstCaseStabilityMargin);

fprintf(fid, ...
    'All tested cases stable     = %d\n\n', ...
    allCasesStable);

fprintf(fid, ...
    'WORKING RANGE\n');

fprintf(fid, ...
    'Maximum suspension deflection = %.3f mm\n', ...
    maxSuspDeflection);

fprintf(fid, ...
    'Maximum suspension velocity   = %.3f m/s\n', ...
    maxSuspVelocity);

fprintf(fid, ...
    'Maximum tyre deflection        = %.3f mm\n', ...
    maxTyreDeflection);

fprintf(fid, ...
    'Maximum actuator utilization   = %.2f %%\n', ...
    maxActuatorUtilization);

fprintf(fid, ...
    'Minimum predicted tyre load    = %.2f N\n', ...
    minTyreLoad);

fprintf(fid, ...
    'Maximum contact-loss time      = %.4f %%\n', ...
    maxContactLoss);

fclose(fid);

%% =========================================================
% Plot 1 - Final Controller Bump Benchmark
% ==========================================================

bumpPassive = [ ...
    passivePeakHeave, ...
    passivePeakPitch, ...
    passiveRMSHeave, ...
    passiveRMSPitch, ...
    passiveSettling];

bumpSky = [ ...
    skyhookPeakHeave, ...
    skyhookPeakPitch, ...
    skyhookRMSHeave, ...
    skyhookRMSPitch, ...
    skyhookSettling];

bumpLQR = [ ...
    lqrPeakHeave, ...
    lqrPeakPitch, ...
    lqrRMSHeave, ...
    lqrRMSPitch, ...
    lqrSettling];

bumpNorm = [ ...
    bumpLQR./bumpPassive; ...
    bumpSky./bumpPassive; ...
    bumpPassive./bumpPassive] * 100;

fig1 = figure( ...
    'Name', ...
    'Final Validation - Symmetric Bump', ...
    'NumberTitle', ...
    'off');

bar(bumpNorm)

grid on

ylabel('Metric [% of Passive]')
title('Final Controller Validation - Symmetric Bump')

xticklabels({ ...
    'Final Tuned LQR', ...
    'Optimized Skyhook', ...
    'Passive'});

legend( ...
    'Peak Heave', ...
    'Peak Pitch', ...
    'RMS Heave Accel', ...
    'RMS Pitch Accel', ...
    'Settling Time', ...
    'Location','best');

bumpPNG = fullfile( ...
    plotsFolder, ...
    'final_validation_bump_summary.png');

bumpFIG = fullfile( ...
    plotsFolder, ...
    'final_validation_bump_summary.fig');

exportgraphics(fig1,bumpPNG,'Resolution',300);
savefig(fig1,bumpFIG);

%% =========================================================
% Plot 2 - Final Controller Kerb Benchmark
% ==========================================================

kerbPassive = [ ...
    passiveKerbHeave, ...
    passiveKerbPitch, ...
    passiveKerbRoll, ...
    passiveKerbRMSRoll, ...
    passiveKerbSettling];

kerbSky = [ ...
    skyhookKerbHeave, ...
    skyhookKerbPitch, ...
    skyhookKerbRoll, ...
    skyhookKerbRMSRoll, ...
    skyhookKerbSettling];

kerbLQR = [ ...
    lqrKerbHeave, ...
    lqrKerbPitch, ...
    lqrKerbRoll, ...
    lqrKerbRMSRoll, ...
    lqrKerbSettling];

kerbNorm = [ ...
    kerbLQR./kerbPassive; ...
    kerbSky./kerbPassive; ...
    kerbPassive./kerbPassive] * 100;

fig2 = figure( ...
    'Name', ...
    'Final Validation - Asymmetric Kerb', ...
    'NumberTitle', ...
    'off');

bar(kerbNorm)

grid on

ylabel('Metric [% of Passive]')
title('Final Controller Validation - Asymmetric Kerb')

xticklabels({ ...
    'Final Tuned LQR', ...
    'Optimized Skyhook', ...
    'Passive'});

legend( ...
    'Peak Heave', ...
    'Peak Pitch', ...
    'Peak Roll', ...
    'RMS Roll Accel', ...
    'Roll Settling', ...
    'Location','best');

kerbPNG = fullfile( ...
    plotsFolder, ...
    'final_validation_kerb_summary.png');

kerbFIG = fullfile( ...
    plotsFolder, ...
    'final_validation_kerb_summary.fig');

exportgraphics(fig2,kerbPNG,'Resolution',300);
savefig(fig2,kerbFIG);

%% =========================================================
% Plot 3 - Robustness and Stability Summary
% ==========================================================

fig3 = figure( ...
    'Name', ...
    'Final Robustness and Stability Summary', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

bar([ ...
    lqrSensitivity, ...
    skySensitivity]);

grid on

ylabel('Mean Sensitivity [%]')
title('Controller Sensitivity to Parameter Uncertainty')

xticklabels({ ...
    'Final Tuned LQR', ...
    'Optimized Skyhook'});

subplot(2,1,2)

bar([ ...
    nominalStabilityMargin, ...
    worstCaseStabilityMargin]);

grid on

ylabel('Stability Margin [1/s]')
title('Final LQR Closed-Loop Stability Margin')

xticklabels({ ...
    'Nominal', ...
    'Worst Parameter Case'});

robustPNG = fullfile( ...
    plotsFolder, ...
    'final_validation_robustness_stability.png');

robustFIG = fullfile( ...
    plotsFolder, ...
    'final_validation_robustness_stability.fig');

exportgraphics(fig3,robustPNG,'Resolution',300);
savefig(fig3,robustFIG);

%% =========================================================
% Plot 4 - Operating Envelope Summary
% ==========================================================

fig4 = figure( ...
    'Name', ...
    'Final Operating Envelope Summary', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

bar([ ...
    maxSuspDeflection, ...
    maxTyreDeflection]);

grid on

ylabel('Deflection [mm]')
title('Maximum Working-Range Deflections')

xticklabels({ ...
    'Suspension', ...
    'Tyre'});

subplot(2,1,2)

bar(maxActuatorUtilization)

hold on

yline( ...
    100, ...
    '--', ...
    'Actuator Limit');

grid on

ylabel('Utilization [%]')
title('Maximum Actuator Utilization')

xticks(1)
xticklabels({'Final Tuned LQR'})

ylim([0 110])

operatingPNG = fullfile( ...
    plotsFolder, ...
    'final_validation_operating_envelope.png');

operatingFIG = fullfile( ...
    plotsFolder, ...
    'final_validation_operating_envelope.fig');

exportgraphics(fig4,operatingPNG,'Resolution',300);
savefig(fig4,operatingFIG);

%% =========================================================
% Plot 5 - Final Key Improvements
% ==========================================================

improvementLabels = { ...
    'Bump Heave', ...
    'Bump Pitch', ...
    'Bump Settling', ...
    'Kerb Heave', ...
    'Kerb Pitch', ...
    'Kerb Roll', ...
    'Kerb Settling'};

improvementValues = [ ...
    lqrBumpHeaveImprove, ...
    lqrBumpPitchImprove, ...
    lqrBumpSettlingImprove, ...
    lqrKerbHeaveImprove, ...
    lqrKerbPitchImprove, ...
    lqrKerbRollImprove, ...
    lqrKerbSettlingImprove];

fig5 = figure( ...
    'Name', ...
    'Final Tuned LQR Improvement Summary', ...
    'NumberTitle', ...
    'off');

bar(improvementValues)

grid on

ylabel('Improvement vs Passive [%]')
title('Final Tuned LQR - Key Performance Improvements')

xticks(1:numel(improvementLabels))
xticklabels(improvementLabels)
xtickangle(20)

improvementPNG = fullfile( ...
    plotsFolder, ...
    'final_validation_lqr_improvements.png');

improvementFIG = fullfile( ...
    plotsFolder, ...
    'final_validation_lqr_improvements.fig');

exportgraphics(fig5,improvementPNG,'Resolution',300);
savefig(fig5,improvementFIG);

%% =========================================================
% Final Confirmation
% ==========================================================

disp(' ')
disp('====================================================')
disp('FINAL VALIDATION SUMMARY SAVED SUCCESSFULLY')
disp('====================================================')

fprintf('\nResults:\n');

fprintf('%s\n',txtFile);
fprintf('%s\n',summaryCSV);
fprintf('%s\n',indicatorCSV);
fprintf('%s\n',matFile);

fprintf('\nPlots:\n');

fprintf('%s\n',bumpPNG);
fprintf('%s\n',kerbPNG);
fprintf('%s\n',robustPNG);
fprintf('%s\n',operatingPNG);
fprintf('%s\n',improvementPNG);
