%% Load Initial LQR Controller

scriptFolder = fileparts(mfilename('fullpath'));
projectFolder = fileparts(fileparts(scriptFolder));

controllerFile = fullfile( ...
    projectFolder, ...
    'Results', ...
    'LQR', ...
    'initial_lqr_controller.mat');

if ~isfile(controllerFile)

    error( ...
        ['Initial LQR controller file not found. ' ...
        'Run design_initial_lqr first.']);

end

controllerData = load( ...
    controllerFile, ...
    'K_lqr');

K_lqr = controllerData.K_lqr;

fprintf( ...
    'LQR controller loaded: K_lqr = %d x %d\n', ...
    size(K_lqr,1), ...
    size(K_lqr,2));
