%% Final LQR Candidate Kerb Sweep
% Compares the two strongest bump candidates on asymmetric kerb input
% and selects the final tuned LQR controller.

clc;

%% =========================================================
% Project Folders
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'LQR');
plotsFolder = fullfile(projectFolder, 'Plots', 'LQR');

if ~exist(plotsFolder, 'dir')
    mkdir(plotsFolder);
end


%% =========================================================
% Load LQR Design Data
% ==========================================================

ctrl = load(fullfile( ...
    resultsFolder, ...
    'initial_lqr_controller.mat'));

A_norm = ctrl.A_norm;
B_norm = ctrl.B_norm;

Sx = ctrl.Sx;
Su = ctrl.Su;


%% =========================================================
% Load Bump Sweep
% ==========================================================

bumpData = load(fullfile( ...
    resultsFolder, ...
    'lqr_candidate_bump_sweep.mat'));

bumpTable = bumpData.candidateTable;


%% =========================================================
% Load Passive Kerb Baseline
% ==========================================================

passiveKerb = load(fullfile( ...
    passiveResultsFolder, ...
    'passive_kerb_metrics.mat'));


%% =========================================================
% Base LQR Weight Structure
% ==========================================================

Q_base = diag([ ...
    8 ...
    20 ...
    20 ...
    1 ...
    1 ...
    1 ...
    1 ...
    5 ...
    8 ...
    8 ...
    0.5 ...
    0.5 ...
    0.5 ...
    0.5]);

R_base = eye(4);


%% =========================================================
% Final Candidates
% ==========================================================

ratioList = [ ...
    0.125 ...
    0.25];

nCases = length(ratioList);


%% =========================================================
% Preallocate
% ==========================================================

Ratio = zeros(nCases,1);

PeakHeave_mm = zeros(nCases,1);
PeakPitch_deg = zeros(nCases,1);
PeakRoll_deg = zeros(nCases,1);

RMSHeaveAccel_mps2 = zeros(nCases,1);
RMSPitchAccel_degps2 = zeros(nCases,1);
RMSRollAccel_degps2 = zeros(nCases,1);

RollSettlingTime_s = zeros(nCases,1);

PeakForce_N = zeros(nCases,1);
MeanRMSForce_N = zeros(nCases,1);

MaxSaturation_pct = zeros(nCases,1);


%% =========================================================
% Simulink Model
% ==========================================================

modelName = ...
    'RaceCar_7DOF_ActiveSuspension';

oldFolder = pwd;

cd(fullfile(projectFolder, 'Model'));

load_system(modelName);


%% =========================================================
% Candidate Simulations
% ==========================================================

disp('====================================================')
disp('FINAL LQR CANDIDATE - ASYMMETRIC KERB SWEEP')
disp('====================================================')

for k = 1:nCases

    ratio = ratioList(k);

    fprintf( ...
        '\nRunning Q/R = %.3f ...\n', ...
        ratio);


    %% -----------------------------------------------------
    % Design Controller
    % ------------------------------------------------------

    Q_candidate = ...
        ratio * Q_base;

    R_candidate = ...
        R_base;

    [K_norm, ~, ~] = ...
        lqr( ...
            A_norm, ...
            B_norm, ...
            Q_candidate, ...
            R_candidate);

    K_candidate = ...
        Su * (K_norm / Sx);


    %% -----------------------------------------------------
    % Send Controller to Simulink
    % ------------------------------------------------------

    assignin( ...
        'base', ...
        'K_lqr', ...
        K_candidate);

    assignin( ...
        'base', ...
        'active_mode', ...
        1);

    assignin( ...
        'base', ...
        'F_act_max', ...
        3000);


    %% -----------------------------------------------------
    % Simulation
    % ------------------------------------------------------

    simOut = sim( ...
        modelName, ...
        'StopTime', ...
        '5', ...
        'ReturnWorkspaceOutputs', ...
        'on');


    %% -----------------------------------------------------
    % Logged Signals
    % ------------------------------------------------------

    z_s_sig = getLoggedSignal( ...
        simOut, ...
        'z_s_out');

    theta_sig = getLoggedSignal( ...
        simOut, ...
        'theta_out');

    phi_sig = getLoggedSignal( ...
        simOut, ...
        'phi_out');

    z_s_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'z_s_ddot_out');

    theta_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'theta_ddot_out');

    phi_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'phi_ddot_out');

    FL_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_FL_out');

    FR_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_FR_out');

    RL_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_RL_out');

    RR_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_RR_out');


    %% -----------------------------------------------------
    % Data
    % ------------------------------------------------------

    t = z_s_sig.Time;

    z_s = z_s_sig.Data;

    theta = ...
        rad2deg(theta_sig.Data);

    phi = ...
        rad2deg(phi_sig.Data);

    z_s_ddot = ...
        z_s_ddot_sig.Data;

    theta_ddot = ...
        rad2deg(theta_ddot_sig.Data);

    phi_ddot = ...
        rad2deg(phi_ddot_sig.Data);

    FL = FL_sig.Data;
    FR = FR_sig.Data;
    RL = RL_sig.Data;
    RR = RR_sig.Data;


    %% -----------------------------------------------------
    % Body Metrics
    % ------------------------------------------------------

    PeakHeave_mm(k) = ...
        1000 * max(abs(z_s));

    PeakPitch_deg(k) = ...
        max(abs(theta));

    PeakRoll_deg(k) = ...
        max(abs(phi));

    RMSHeaveAccel_mps2(k) = ...
        rms(z_s_ddot);

    RMSPitchAccel_degps2(k) = ...
        rms(theta_ddot);

    RMSRollAccel_degps2(k) = ...
        rms(phi_ddot);


    %% -----------------------------------------------------
    % Roll Settling Time
    % ------------------------------------------------------

    threshold = ...
        0.02 * max(abs(phi));

    settlingTime = NaN;

    for i = 1:length(phi)

        if t(i) >= 1.0

            if all( ...
                    abs(phi(i:end)) ...
                    <= threshold)

                settlingTime = t(i);
                break;

            end

        end

    end

    RollSettlingTime_s(k) = ...
        settlingTime;


    %% -----------------------------------------------------
    % Actuator Metrics
    % ------------------------------------------------------

    PeakForce_N(k) = max([ ...
        max(abs(FL)), ...
        max(abs(FR)), ...
        max(abs(RL)), ...
        max(abs(RR))]);

    MeanRMSForce_N(k) = mean([ ...
        rms(FL), ...
        rms(FR), ...
        rms(RL), ...
        rms(RR)]);

    MaxSaturation_pct(k) = max([ ...
        100*mean(abs(FL) >= 0.999*3000), ...
        100*mean(abs(FR) >= 0.999*3000), ...
        100*mean(abs(RL) >= 0.999*3000), ...
        100*mean(abs(RR) >= 0.999*3000)]);

    Ratio(k) = ratio;


    fprintf( ...
        ['Peak roll = %.5f deg | ' ...
         'RMS roll accel = %.2f deg/s^2 | ' ...
         'Peak force = %.1f N\n'], ...
        PeakRoll_deg(k), ...
        RMSRollAccel_degps2(k), ...
        PeakForce_N(k));

end


cd(oldFolder);


%% =========================================================
% Kerb Results Table
% ==========================================================

kerbTable = table( ...
    Ratio, ...
    PeakHeave_mm, ...
    PeakPitch_deg, ...
    PeakRoll_deg, ...
    RMSHeaveAccel_mps2, ...
    RMSPitchAccel_degps2, ...
    RMSRollAccel_degps2, ...
    RollSettlingTime_s, ...
    PeakForce_N, ...
    MeanRMSForce_N, ...
    MaxSaturation_pct);


%% =========================================================
% Normalize Kerb Metrics
% ==========================================================

normHeaveKerb = ...
    PeakHeave_mm / passiveKerb.peak_heave_mm;

normPitchKerb = ...
    PeakPitch_deg / passiveKerb.peak_pitch_deg;

normRollKerb = ...
    PeakRoll_deg / passiveKerb.peak_roll_deg;

normHeaveAccelKerb = ...
    RMSHeaveAccel_mps2 / passiveKerb.rms_heave_accel;

normPitchAccelKerb = ...
    RMSPitchAccel_degps2 / passiveKerb.rms_pitch_accel;

normRollAccelKerb = ...
    RMSRollAccel_degps2 / passiveKerb.rms_roll_accel;

normSettlingKerb = ...
    RollSettlingTime_s / passiveKerb.roll_settling_time;

normForceKerb = ...
    PeakForce_N / 3000;


%% =========================================================
% Kerb Objective
% ==========================================================
%
% Lower = better.
%
% Roll is given additional importance because this is an
% asymmetric motorsport disturbance.

kerbScore = ...
      0.10 * normHeaveKerb ...
    + 0.10 * normPitchKerb ...
    + 0.15 * normRollKerb ...
    + 0.15 * normHeaveAccelKerb ...
    + 0.15 * normPitchAccelKerb ...
    + 0.15 * normRollAccelKerb ...
    + 0.10 * normSettlingKerb ...
    + 0.10 * normForceKerb;

kerbTable.KerbObjective = ...
    kerbScore;


%% =========================================================
% Retrieve Matching Bump Scores
% ==========================================================

bumpScore = zeros(nCases,1);

for k = 1:nCases

    idx = find( ...
        abs(bumpTable.Ratio - Ratio(k)) < 1e-9, ...
        1);

    if isempty(idx)

        error( ...
            'Matching bump candidate not found.');

    end

    bumpScore(k) = ...
        bumpTable.ObjectiveScore(idx);

end


%% =========================================================
% Combined Bump + Kerb Objective
% ==========================================================
%
% Both scenarios are given equal importance.

combinedScore = ...
    0.50 * bumpScore + ...
    0.50 * kerbScore;

kerbTable.BumpObjective = ...
    bumpScore;

kerbTable.CombinedObjective = ...
    combinedScore;


%% =========================================================
% Select Final LQR
% ==========================================================

[bestCombinedScore, bestIdx] = ...
    min(combinedScore);

finalRatio = ...
    Ratio(bestIdx);


%% =========================================================
% Rebuild Final Controller
% ==========================================================

Q_final = ...
    finalRatio * Q_base;

R_final = ...
    R_base;

[K_norm_final, ~, ~] = ...
    lqr( ...
        A_norm, ...
        B_norm, ...
        Q_final, ...
        R_final);

K_lqr_final = ...
    Su * (K_norm_final / Sx);


%% =========================================================
% Display Results
% ==========================================================

disp(' ')
disp('====================================================')
disp('FINAL LQR CANDIDATE RESULTS')
disp('====================================================')

disp(kerbTable)

disp(' ')
disp('FINAL TUNED LQR')
disp('----------------------------------------------------')

fprintf( ...
    'Selected Q/R ratio      = %.3f\n', ...
    finalRatio);

fprintf( ...
    'Combined objective      = %.6f\n', ...
    bestCombinedScore);

fprintf( ...
    'Kerb peak heave         = %.4f mm\n', ...
    PeakHeave_mm(bestIdx));

fprintf( ...
    'Kerb peak pitch         = %.5f deg\n', ...
    PeakPitch_deg(bestIdx));

fprintf( ...
    'Kerb peak roll          = %.5f deg\n', ...
    PeakRoll_deg(bestIdx));

fprintf( ...
    'Kerb RMS roll accel     = %.3f deg/s^2\n', ...
    RMSRollAccel_degps2(bestIdx));

fprintf( ...
    'Kerb roll settling      = %.3f s\n', ...
    RollSettlingTime_s(bestIdx));

fprintf( ...
    'Kerb peak force         = %.2f N\n', ...
    PeakForce_N(bestIdx));

disp('====================================================')


%% =========================================================
% Save Final Controller
% ==========================================================

controllerFile = fullfile( ...
    resultsFolder, ...
    'final_tuned_lqr_controller.mat');

save(controllerFile, ...
    'K_lqr_final', ...
    'K_norm_final', ...
    'Q_final', ...
    'R_final', ...
    'finalRatio', ...
    'bestCombinedScore', ...
    'Sx', ...
    'Su');


%% =========================================================
% Save Candidate Results
% ==========================================================

csvFile = fullfile( ...
    resultsFolder, ...
    'lqr_final_candidate_kerb_sweep.csv');

writetable(kerbTable, csvFile);

matFile = fullfile( ...
    resultsFolder, ...
    'lqr_final_candidate_kerb_sweep.mat');

save(matFile, ...
    'kerbTable', ...
    'finalRatio', ...
    'bestCombinedScore', ...
    'bestIdx');


%% =========================================================
% Save TXT
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'lqr_final_candidate_kerb_sweep.txt');

fid = fopen(txtFile, 'w');

fprintf(fid, ...
    'FINAL LQR CANDIDATE SELECTION\n');

fprintf(fid, ...
    '=============================\n\n');

for k = 1:nCases

    fprintf(fid, ...
        'Q/R ratio = %.3f\n', ...
        Ratio(k));

    fprintf(fid, ...
        'Peak heave = %.5f mm\n', ...
        PeakHeave_mm(k));

    fprintf(fid, ...
        'Peak pitch = %.6f deg\n', ...
        PeakPitch_deg(k));

    fprintf(fid, ...
        'Peak roll = %.6f deg\n', ...
        PeakRoll_deg(k));

    fprintf(fid, ...
        'RMS heave accel = %.6f m/s^2\n', ...
        RMSHeaveAccel_mps2(k));

    fprintf(fid, ...
        'RMS pitch accel = %.6f deg/s^2\n', ...
        RMSPitchAccel_degps2(k));

    fprintf(fid, ...
        'RMS roll accel = %.6f deg/s^2\n', ...
        RMSRollAccel_degps2(k));

    fprintf(fid, ...
        'Roll settling = %.6f s\n', ...
        RollSettlingTime_s(k));

    fprintf(fid, ...
        'Peak force = %.2f N\n', ...
        PeakForce_N(k));

    fprintf(fid, ...
        'Bump objective = %.6f\n', ...
        bumpScore(k));

    fprintf(fid, ...
        'Kerb objective = %.6f\n', ...
        kerbScore(k));

    fprintf(fid, ...
        'Combined objective = %.6f\n\n', ...
        combinedScore(k));

end

fprintf(fid, ...
    'FINAL Q/R RATIO = %.3f\n', ...
    finalRatio);

fprintf(fid, ...
    'FINAL COMBINED OBJECTIVE = %.6f\n', ...
    bestCombinedScore);

fclose(fid);


%% =========================================================
% Performance Plot
% ==========================================================

plotData = [ ...
    100*normHeaveKerb ...
    100*normPitchKerb ...
    100*normRollKerb ...
    100*normHeaveAccelKerb ...
    100*normPitchAccelKerb ...
    100*normRollAccelKerb ...
    100*normSettlingKerb];

metricNames = { ...
    'Peak Heave', ...
    'Peak Pitch', ...
    'Peak Roll', ...
    'RMS Heave Accel', ...
    'RMS Pitch Accel', ...
    'RMS Roll Accel', ...
    'Roll Settling'};

fig1 = figure( ...
    'Name', ...
    'Final LQR Kerb Candidates', ...
    'NumberTitle', ...
    'off');

bar( ...
    categorical(metricNames), ...
    plotData');

grid on

ylabel('Metric [% of Passive]')

title('Final LQR Candidate Comparison - Asymmetric Kerb')

legend( ...
    'Q/R = 0.125', ...
    'Q/R = 0.25', ...
    'Location', ...
    'best');

performancePNG = fullfile( ...
    plotsFolder, ...
    'lqr_final_candidate_kerb_performance.png');

performanceFIG = fullfile( ...
    plotsFolder, ...
    'lqr_final_candidate_kerb_performance.fig');

exportgraphics( ...
    fig1, ...
    performancePNG, ...
    'Resolution', ...
    300);

savefig(fig1, performanceFIG);


%% =========================================================
% Combined Objective Plot
% ==========================================================

fig2 = figure( ...
    'Name', ...
    'Final LQR Selection', ...
    'NumberTitle', ...
    'off');

bar( ...
    categorical(string(Ratio)), ...
    combinedScore);

grid on

xlabel('Q/R Ratio')
ylabel('Combined Objective Score')

title('Final LQR Selection - Bump + Kerb');

objectivePNG = fullfile( ...
    plotsFolder, ...
    'lqr_final_combined_objective.png');

objectiveFIG = fullfile( ...
    plotsFolder, ...
    'lqr_final_combined_objective.fig');

exportgraphics( ...
    fig2, ...
    objectivePNG, ...
    'Resolution', ...
    300);

savefig(fig2, objectiveFIG);


%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('Final LQR candidate selection saved successfully.');

fprintf('\nFinal controller:\n');
fprintf('%s\n', controllerFile);

fprintf('\nResults:\n');
fprintf('%s\n', txtFile);
fprintf('%s\n', csvFile);
fprintf('%s\n', matFile);

fprintf('\nPlots:\n');
fprintf('%s\n', performancePNG);
fprintf('%s\n', objectivePNG);


%% =========================================================
% Helper Function
% ==========================================================

function sig = getLoggedSignal(simOut, signalName)

    try

        sig = simOut.get(signalName);

        if ~isempty(sig)
            return;
        end

    catch
    end

    if evalin( ...
            'base', ...
            sprintf( ...
                'exist(''%s'',''var'')', ...
                signalName))

        sig = evalin( ...
            'base', ...
            signalName);

        return;

    end

    error( ...
        'Unable to locate logged signal: %s', ...
        signalName);

end
