%% LQR Candidate Symmetric-Bump Sweep
% Evaluates selected LQR aggressiveness levels using the Simulink plant.

clc;

%% =========================================================
% Project Folders
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'LQR');
plotsFolder = fullfile(projectFolder, 'Plots', 'LQR');

if ~exist(plotsFolder, 'dir')
    mkdir(plotsFolder);
end

%% =========================================================
% Load Existing LQR Design Data
% ==========================================================

controllerFile = fullfile( ...
    resultsFolder, ...
    'initial_lqr_controller.mat');

if ~isfile(controllerFile)
    error('initial_lqr_controller.mat not found.');
end

ctrl = load(controllerFile);

A_norm = ctrl.A_norm;
B_norm = ctrl.B_norm;
Sx = ctrl.Sx;
Su = ctrl.Su;

%% =========================================================
% Base LQR Weights
% ==========================================================

Q_base = diag([ ...
    8 ...
    20 ...
    20 ...
    1 ...
    1 ...
    1 ...
    1 ...
    5 ...
    8 ...
    8 ...
    0.5 ...
    0.5 ...
    0.5 ...
    0.5]);

R_base = eye(4);

%% =========================================================
% Candidate Aggressiveness Ratios
% ==========================================================
%
% Since uniform Q/R scaling gives equivalent LQR solutions,
% we test unique Q/R ratios only.

ratioList = [ ...
    0.125 ...
    0.25 ...
    0.50 ...
    1.00];

nCases = length(ratioList);

%% =========================================================
% Preallocate Results
% ==========================================================

Ratio = zeros(nCases,1);

PeakHeave_mm = zeros(nCases,1);
PeakPitch_deg = zeros(nCases,1);

RMSHeaveAccel_mps2 = zeros(nCases,1);
RMSPitchAccel_degps2 = zeros(nCases,1);

SettlingTime_s = zeros(nCases,1);

PeakForce_N = zeros(nCases,1);
MeanRMSForce_N = zeros(nCases,1);

MaxSaturation_pct = zeros(nCases,1);

GainNorm = zeros(nCases,1);

%% =========================================================
% Model
% ==========================================================

modelName = 'RaceCar_7DOF_ActiveSuspension';

oldFolder = pwd;
cd(fullfile(projectFolder, 'Model'));

load_system(modelName);

%% =========================================================
% Sweep
% ==========================================================

disp('====================================================')
disp('LQR CANDIDATE SYMMETRIC-BUMP SWEEP')
disp('====================================================')

for k = 1:nCases

    ratio = ratioList(k);

    fprintf( ...
        '\nRunning LQR candidate %d/%d: Q/R = %.3f\n', ...
        k, nCases, ratio);

    %% -----------------------------------------------------
    % Design Candidate Controller
    % ------------------------------------------------------

    Q_candidate = ratio * Q_base;

    R_candidate = R_base;

    [K_norm, ~, ~] = ...
        lqr( ...
            A_norm, ...
            B_norm, ...
            Q_candidate, ...
            R_candidate);

    K_candidate = ...
        Su * (K_norm / Sx);

    GainNorm(k) = ...
        norm(K_candidate, 'fro');

    %% Make Simulink use this controller

    assignin( ...
        'base', ...
        'K_lqr', ...
        K_candidate);

    assignin( ...
        'base', ...
        'active_mode', ...
        1);

    assignin( ...
        'base', ...
        'F_act_max', ...
        3000);

    %% -----------------------------------------------------
    % Run Simulation
    % ------------------------------------------------------

    simOut = sim( ...
        modelName, ...
        'StopTime', ...
        '5', ...
        'ReturnWorkspaceOutputs', ...
        'on');

    %% -----------------------------------------------------
    % Extract Signals
    % ------------------------------------------------------

    z_s_sig = getLoggedSignal( ...
        simOut, ...
        'z_s_out');

    theta_sig = getLoggedSignal( ...
        simOut, ...
        'theta_out');

    z_s_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'z_s_ddot_out');

    theta_ddot_sig = getLoggedSignal( ...
        simOut, ...
        'theta_ddot_out');

    FL_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_FL_out');

    FR_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_FR_out');

    RL_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_RL_out');

    RR_sig = getLoggedSignal( ...
        simOut, ...
        'F_act_RR_out');

    %% -----------------------------------------------------
    % Convert Data
    % ------------------------------------------------------

    t = z_s_sig.Time;

    z_s = z_s_sig.Data;

    theta_deg = ...
        rad2deg(theta_sig.Data);

    z_s_ddot = ...
        z_s_ddot_sig.Data;

    theta_ddot_deg = ...
        rad2deg(theta_ddot_sig.Data);

    FL = FL_sig.Data;
    FR = FR_sig.Data;
    RL = RL_sig.Data;
    RR = RR_sig.Data;

    %% -----------------------------------------------------
    % Metrics
    % ------------------------------------------------------

    PeakHeave_mm(k) = ...
        1000 * max(abs(z_s));

    PeakPitch_deg(k) = ...
        max(abs(theta_deg));

    RMSHeaveAccel_mps2(k) = ...
        rms(z_s_ddot);

    RMSPitchAccel_degps2(k) = ...
        rms(theta_ddot_deg);

    %% Settling time

    threshold = ...
        0.02 * max(abs(z_s));

    settlingTime = NaN;

    for i = 1:length(z_s)

        if t(i) >= 1.0

            if all( ...
                abs(z_s(i:end)) ...
                <= threshold)

                settlingTime = t(i);
                break;

            end

        end

    end

    SettlingTime_s(k) = ...
        settlingTime;

    %% Actuator effort

    PeakForce_N(k) = max([ ...
        max(abs(FL)), ...
        max(abs(FR)), ...
        max(abs(RL)), ...
        max(abs(RR))]);

    MeanRMSForce_N(k) = mean([ ...
        rms(FL), ...
        rms(FR), ...
        rms(RL), ...
        rms(RR)]);

    MaxSaturation_pct(k) = max([ ...
        100*mean(abs(FL) >= 0.999*3000), ...
        100*mean(abs(FR) >= 0.999*3000), ...
        100*mean(abs(RL) >= 0.999*3000), ...
        100*mean(abs(RR) >= 0.999*3000)]);

    Ratio(k) = ratio;

    fprintf( ...
        ['Peak heave = %.4f mm | ' ...
         'RMS heave accel = %.4f m/s^2 | ' ...
         'Peak force = %.1f N\n'], ...
        PeakHeave_mm(k), ...
        RMSHeaveAccel_mps2(k), ...
        PeakForce_N(k));

end

cd(oldFolder);

%% =========================================================
% Restore Initial LQR
% ==========================================================

assignin( ...
    'base', ...
    'K_lqr', ...
    ctrl.K_lqr);

%% =========================================================
% Results Table
% ==========================================================

candidateTable = table( ...
    Ratio, ...
    PeakHeave_mm, ...
    PeakPitch_deg, ...
    RMSHeaveAccel_mps2, ...
    RMSPitchAccel_degps2, ...
    SettlingTime_s, ...
    PeakForce_N, ...
    MeanRMSForce_N, ...
    MaxSaturation_pct, ...
    GainNorm);

disp(' ')
disp('====================================================')
disp('LQR CANDIDATE BUMP RESULTS')
disp('====================================================')

disp(candidateTable)

%% =========================================================
% Load Passive Baseline
% ==========================================================

passive = load(fullfile( ...
    passiveResultsFolder, ...
    'passive_baseline_summary.mat'));

%% =========================================================
% Normalized Metrics
% ==========================================================

NormHeave = ...
    PeakHeave_mm / passive.peak_heave_mm;

NormPitch = ...
    PeakPitch_deg / passive.peak_pitch_deg;

NormHeaveAccel = ...
    RMSHeaveAccel_mps2 / passive.rms_heave_accel;

NormPitchAccel = ...
    RMSPitchAccel_degps2 / passive.rms_pitch_accel;

NormSettling = ...
    SettlingTime_s / passive.settling_time;

NormForce = ...
    PeakForce_N / 3000;

%% =========================================================
% Preliminary Weighted Score
% ==========================================================
%
% Lower score = better.
%
% Acceleration and actuator effort receive relatively strong
% weighting because the initial LQR was already strong in
% body-motion suppression but too aggressive.

ObjectiveScore = ...
      0.15 * NormHeave ...
    + 0.15 * NormPitch ...
    + 0.20 * NormHeaveAccel ...
    + 0.20 * NormPitchAccel ...
    + 0.10 * NormSettling ...
    + 0.20 * NormForce;

candidateTable.ObjectiveScore = ...
    ObjectiveScore;

[bestScore, bestIdx] = ...
    min(ObjectiveScore);

bestRatio = ...
    Ratio(bestIdx);

%% =========================================================
% Display Preliminary Best Candidate
% ==========================================================

disp(' ')
disp('====================================================')
disp('PRELIMINARY BEST BUMP CANDIDATE')
disp('====================================================')

fprintf( ...
    'Q/R ratio         = %.3f\n', ...
    bestRatio);

fprintf( ...
    'Objective score   = %.6f\n', ...
    bestScore);

fprintf( ...
    'Peak heave        = %.4f mm\n', ...
    PeakHeave_mm(bestIdx));

fprintf( ...
    'Peak pitch        = %.5f deg\n', ...
    PeakPitch_deg(bestIdx));

fprintf( ...
    'RMS heave accel   = %.5f m/s^2\n', ...
    RMSHeaveAccel_mps2(bestIdx));

fprintf( ...
    'RMS pitch accel   = %.5f deg/s^2\n', ...
    RMSPitchAccel_degps2(bestIdx));

fprintf( ...
    'Settling time     = %.3f s\n', ...
    SettlingTime_s(bestIdx));

fprintf( ...
    'Peak force        = %.2f N\n', ...
    PeakForce_N(bestIdx));

disp('====================================================')

%% =========================================================
% Save Results
% ==========================================================

csvFile = fullfile( ...
    resultsFolder, ...
    'lqr_candidate_bump_sweep.csv');

writetable( ...
    candidateTable, ...
    csvFile);

matFile = fullfile( ...
    resultsFolder, ...
    'lqr_candidate_bump_sweep.mat');

save(matFile, ...
    'candidateTable', ...
    'ratioList', ...
    'bestRatio', ...
    'bestIdx', ...
    'bestScore');

txtFile = fullfile( ...
    resultsFolder, ...
    'lqr_candidate_bump_sweep.txt');

fid = fopen(txtFile, 'w');

fprintf(fid, ...
    'LQR CANDIDATE SYMMETRIC-BUMP SWEEP\n');

fprintf(fid, ...
    '==================================\n\n');

for i = 1:height(candidateTable)

    fprintf(fid, ...
        'Q/R ratio = %.3f\n', ...
        candidateTable.Ratio(i));

    fprintf(fid, ...
        'Peak heave = %.5f mm\n', ...
        candidateTable.PeakHeave_mm(i));

    fprintf(fid, ...
        'Peak pitch = %.6f deg\n', ...
        candidateTable.PeakPitch_deg(i));

    fprintf(fid, ...
        'RMS heave acceleration = %.6f m/s^2\n', ...
        candidateTable.RMSHeaveAccel_mps2(i));

    fprintf(fid, ...
        'RMS pitch acceleration = %.6f deg/s^2\n', ...
        candidateTable.RMSPitchAccel_degps2(i));

    fprintf(fid, ...
        'Settling time = %.5f s\n', ...
        candidateTable.SettlingTime_s(i));

    fprintf(fid, ...
        'Peak actuator force = %.2f N\n', ...
        candidateTable.PeakForce_N(i));

    fprintf(fid, ...
        'Objective score = %.6f\n\n', ...
        candidateTable.ObjectiveScore(i));

end

fprintf(fid, ...
    'Preliminary best Q/R ratio = %.3f\n', ...
    bestRatio);

fprintf(fid, ...
    'Best objective score = %.6f\n', ...
    bestScore);

fclose(fid);

%% =========================================================
% Body-Motion Trade-Off Plot
% ==========================================================

fig1 = figure( ...
    'Name', ...
    'LQR Candidate Body Motion', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

plot( ...
    Ratio, ...
    PeakHeave_mm, ...
    '-o', ...
    'LineWidth', 1.5);

grid on

xlabel('Q/R Ratio')
ylabel('Peak Heave [mm]')

title('Peak Heave vs LQR Aggressiveness');

subplot(2,1,2)

plot( ...
    Ratio, ...
    PeakPitch_deg, ...
    '-o', ...
    'LineWidth', 1.5);

grid on

xlabel('Q/R Ratio')
ylabel('Peak Pitch [deg]')

title('Peak Pitch vs LQR Aggressiveness');

motionPNG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_body_motion.png');

motionFIG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_body_motion.fig');

exportgraphics( ...
    fig1, ...
    motionPNG, ...
    'Resolution', ...
    300);

savefig(fig1, motionFIG);

%% =========================================================
% Acceleration Trade-Off Plot
% ==========================================================

fig2 = figure( ...
    'Name', ...
    'LQR Candidate Acceleration', ...
    'NumberTitle', ...
    'off');

subplot(2,1,1)

plot( ...
    Ratio, ...
    RMSHeaveAccel_mps2, ...
    '-o', ...
    'LineWidth', 1.5);

hold on

yline( ...
    passive.rms_heave_accel, ...
    '--');

grid on

xlabel('Q/R Ratio')
ylabel('RMS Heave Accel [m/s^2]')

title('RMS Heave Acceleration');

subplot(2,1,2)

plot( ...
    Ratio, ...
    RMSPitchAccel_degps2, ...
    '-o', ...
    'LineWidth', 1.5);

hold on

yline( ...
    passive.rms_pitch_accel, ...
    '--');

grid on

xlabel('Q/R Ratio')
ylabel('RMS Pitch Accel [deg/s^2]')

title('RMS Pitch Acceleration');

accelPNG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_acceleration.png');

accelFIG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_acceleration.fig');

exportgraphics( ...
    fig2, ...
    accelPNG, ...
    'Resolution', ...
    300);

savefig(fig2, accelFIG);

%% =========================================================
% Actuator-Effort Plot
% ==========================================================

fig3 = figure( ...
    'Name', ...
    'LQR Candidate Actuator Effort', ...
    'NumberTitle', ...
    'off');

plot( ...
    Ratio, ...
    PeakForce_N, ...
    '-o', ...
    'LineWidth', 1.5);

hold on

yline( ...
    3000, ...
    '--');

grid on

xlabel('Q/R Ratio')
ylabel('Peak Actuator Force [N]')

title('Peak Actuator Force vs LQR Aggressiveness');

forcePNG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_actuator_effort.png');

forceFIG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_actuator_effort.fig');

exportgraphics( ...
    fig3, ...
    forcePNG, ...
    'Resolution', ...
    300);

savefig(fig3, forceFIG);

%% =========================================================
% Objective Score Plot
% ==========================================================

fig4 = figure( ...
    'Name', ...
    'LQR Candidate Objective Score', ...
    'NumberTitle', ...
    'off');

plot( ...
    Ratio, ...
    ObjectiveScore, ...
    '-o', ...
    'LineWidth', 1.5);

hold on

plot( ...
    bestRatio, ...
    bestScore, ...
    'o', ...
    'MarkerSize', 10, ...
    'LineWidth', 2);

grid on

xlabel('Q/R Ratio')
ylabel('Weighted Objective Score')

title('LQR Symmetric-Bump Candidate Selection');

scorePNG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_objective.png');

scoreFIG = fullfile( ...
    plotsFolder, ...
    'lqr_candidate_bump_objective.fig');

exportgraphics( ...
    fig4, ...
    scorePNG, ...
    'Resolution', ...
    300);

savefig(fig4, scoreFIG);

%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('LQR candidate bump sweep saved successfully.');

fprintf('\nResults:\n');
fprintf('%s\n', txtFile);
fprintf('%s\n', csvFile);
fprintf('%s\n', matFile);

fprintf('\nPlots:\n');
fprintf('%s\n', motionPNG);
fprintf('%s\n', accelPNG);
fprintf('%s\n', forcePNG);
fprintf('%s\n', scorePNG);

%% =========================================================
% Local Helper Function
% ==========================================================

function sig = getLoggedSignal(simOut, signalName)

    try
        sig = simOut.get(signalName);

        if ~isempty(sig)
            return;
        end
    catch
    end

    if evalin('base', ...
            sprintf('exist(''%s'',''var'')', signalName))

        sig = evalin('base', signalName);
        return;
    end

    error( ...
        'Unable to locate logged signal: %s', ...
        signalName);

end
