%% Kerb Test Conclusions
% Repository-ready summary of asymmetric kerb validation

clc;

%% =========================================================
% Project Folders
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
plotsFolder = fullfile(projectFolder, 'Plots', 'Skyhook');

if ~exist(plotsFolder, 'dir')
    mkdir(plotsFolder);
end


%% =========================================================
% Load Kerb Trade-Off Results
% ==========================================================

dataFile = fullfile( ...
    resultsFolder, ...
    'kerb_tradeoff_summary.mat');

if ~isfile(dataFile)
    error('kerb_tradeoff_summary.mat not found.');
end

data = load(dataFile);


%% =========================================================
% Extract Results
% ==========================================================

peakHeaveReduction = data.peakHeaveImprovement;
peakPitchReduction = data.peakPitchImprovement;
peakRollReduction = data.peakRollImprovement;

heaveAccelReduction = data.heaveAccelImprovement;
pitchAccelReduction = data.pitchAccelImprovement;
rollAccelReduction = data.rollAccelImprovement;

rollSettlingReduction = data.rollSettlingImprovement;

peakActuatorForce = data.peakActuatorForce;
meanRMSActuatorForce = data.meanRMSActuatorForce;
maxSaturation = data.maxSaturation;


%% =========================================================
% Display Repository-Ready Conclusions
% ==========================================================

disp('====================================================')
disp('ASYMMETRIC KERB TEST - FINAL CONCLUSIONS')
disp('====================================================')

fprintf( ...
    'The optimized Skyhook controller reduced peak roll by %.2f %%.\n', ...
    peakRollReduction);

fprintf( ...
    'Peak pitch was reduced by %.2f %%.\n', ...
    peakPitchReduction);

fprintf( ...
    'Peak heave was reduced by %.2f %%.\n', ...
    peakHeaveReduction);

fprintf( ...
    'Roll settling time improved by %.2f %%.\n', ...
    rollSettlingReduction);

fprintf( ...
    'RMS roll acceleration improved by %.2f %%.\n', ...
    rollAccelReduction);

fprintf( ...
    'RMS pitch acceleration improved by %.2f %%.\n', ...
    pitchAccelReduction);

fprintf( ...
    'RMS heave acceleration improved by %.2f %%.\n', ...
    heaveAccelReduction);

fprintf( ...
    'Peak actuator force was %.2f N.\n', ...
    peakActuatorForce);

fprintf( ...
    'Maximum actuator saturation was %.3f %%.\n', ...
    maxSaturation);

disp('====================================================')


%% =========================================================
% Save TXT Conclusions
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'kerb_test_conclusions.txt');

fid = fopen(txtFile, 'w');

fprintf(fid, ...
    'ASYMMETRIC KERB TEST - FINAL CONCLUSIONS\n');

fprintf(fid, ...
    '========================================\n\n');

fprintf(fid, ...
    ['The optimized Skyhook controller was evaluated using a ' ...
     '30 mm left-side kerb excitation at 20 m/s.\n\n']);

fprintf(fid, ...
    'Peak roll reduction: %.2f %%\n', ...
    peakRollReduction);

fprintf(fid, ...
    'Peak pitch reduction: %.2f %%\n', ...
    peakPitchReduction);

fprintf(fid, ...
    'Peak heave reduction: %.2f %%\n', ...
    peakHeaveReduction);

fprintf(fid, ...
    'Roll settling-time improvement: %.2f %%\n', ...
    rollSettlingReduction);

fprintf(fid, ...
    'RMS roll acceleration reduction: %.2f %%\n', ...
    rollAccelReduction);

fprintf(fid, ...
    'RMS pitch acceleration reduction: %.2f %%\n', ...
    pitchAccelReduction);

fprintf(fid, ...
    'RMS heave acceleration reduction: %.2f %%\n\n', ...
    heaveAccelReduction);

fprintf(fid, ...
    'Peak actuator force: %.2f N\n', ...
    peakActuatorForce);

fprintf(fid, ...
    'Mean RMS actuator force: %.2f N\n', ...
    meanRMSActuatorForce);

fprintf(fid, ...
    'Maximum actuator saturation: %.3f %%\n\n', ...
    maxSaturation);

fprintf(fid, ...
    ['Interpretation:\n' ...
     'The optimized Skyhook controller provides strong body-attitude ' ...
     'control under asymmetric kerb excitation, particularly in pitch ' ...
     'and roll. Improvements in body acceleration are smaller, which ' ...
     'indicates that the controller is more effective at reducing body ' ...
     'motion than improving ride acceleration. The actuator force remains ' ...
     'within the imposed 3000 N limit with no saturation.\n']);

fclose(fid);


%% =========================================================
% Save MAT
% ==========================================================

matFile = fullfile( ...
    resultsFolder, ...
    'kerb_test_conclusions.mat');

save(matFile, ...
    'peakHeaveReduction', ...
    'peakPitchReduction', ...
    'peakRollReduction', ...
    'heaveAccelReduction', ...
    'pitchAccelReduction', ...
    'rollAccelReduction', ...
    'rollSettlingReduction', ...
    'peakActuatorForce', ...
    'meanRMSActuatorForce', ...
    'maxSaturation');


%% =========================================================
% Summary Plot
% ==========================================================

categories = categorical({ ...
    'Peak Heave', ...
    'Peak Pitch', ...
    'Peak Roll', ...
    'RMS Heave Accel', ...
    'RMS Pitch Accel', ...
    'RMS Roll Accel', ...
    'Roll Settling'});

values = [ ...
    peakHeaveReduction, ...
    peakPitchReduction, ...
    peakRollReduction, ...
    heaveAccelReduction, ...
    pitchAccelReduction, ...
    rollAccelReduction, ...
    rollSettlingReduction];

fig = figure( ...
    'Name', ...
    'Kerb Test Final Summary', ...
    'NumberTitle', ...
    'off');

bar(categories, values);

grid on

ylabel('Improvement vs Passive [%]')

title('Asymmetric Kerb Test - Final Controller Performance')


%% =========================================================
% Save Plot
% ==========================================================

pngFile = fullfile( ...
    plotsFolder, ...
    'kerb_test_final_summary.png');

figFile = fullfile( ...
    plotsFolder, ...
    'kerb_test_final_summary.fig');

exportgraphics(fig, ...
    pngFile, ...
    'Resolution', 300);

savefig(fig, figFile);


%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('Kerb conclusions saved successfully.');

fprintf('\nResults:\n');
fprintf('%s\n', txtFile);
fprintf('%s\n', matFile);

fprintf('\nPlot:\n');
fprintf('%s\n', pngFile);