%% Skyhook Weighted Gain Optimization

clc;

%% =========================================================
% Project Folders
% ==========================================================

scriptPath = mfilename('fullpath');
scriptFolder = fileparts(scriptPath);
projectFolder = fileparts(fileparts(scriptFolder));

passiveResultsFolder = fullfile(projectFolder, 'Results', 'Passive');
skyhookResultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
lqrResultsFolder = fullfile(projectFolder, 'Results', 'LQR');
robustnessResultsFolder = fullfile(projectFolder, 'Results', 'Robustness');
operatingResultsFolder = fullfile(projectFolder, 'Results', 'Operating_Envelope');
finalResultsFolder = fullfile(projectFolder, 'Results', 'Final');

resultsFolder = fullfile(projectFolder, 'Results', 'Skyhook');
plotsFolder = fullfile(projectFolder, 'Plots', 'Skyhook');

if ~exist(plotsFolder, 'dir')
    mkdir(plotsFolder);
end


%% =========================================================
% Load Gain Sweep
% ==========================================================

sweepFile = fullfile( ...
    resultsFolder, ...
    'skyhook_gain_sweep.mat');

if ~isfile(sweepFile)
    error('skyhook_gain_sweep.mat not found.');
end

sweep = load(sweepFile);

T = sweep.resultsTable;


%% =========================================================
% Load Passive Baseline
% ==========================================================

baselineFile = fullfile( ...
    passiveResultsFolder, ...
    'passive_baseline_summary.mat');

if ~isfile(baselineFile)
    error('passive_baseline_summary.mat not found.');
end

baseline = load(baselineFile);


%% =========================================================
% Optimization Weights
% ==========================================================

w_heave       = 0.20;
w_pitch       = 0.20;
w_heaveAccel  = 0.20;
w_pitchAccel  = 0.15;
w_settling    = 0.15;
w_force       = 0.10;

weight_sum = ...
    w_heave + ...
    w_pitch + ...
    w_heaveAccel + ...
    w_pitchAccel + ...
    w_settling + ...
    w_force;

if abs(weight_sum - 1) > 1e-9
    error('Optimization weights must sum to 1.');
end


%% =========================================================
% Normalize Against Passive Baseline
% ==========================================================

normHeave = ...
    T.peakHeave ./ baseline.peak_heave_mm;

normPitch = ...
    T.peakPitch ./ baseline.peak_pitch_deg;

normHeaveAccel = ...
    T.rmsHeaveAccel ./ baseline.rms_heave_accel;

normPitchAccel = ...
    T.rmsPitchAccel ./ baseline.rms_pitch_accel;

normSettling = ...
    T.settlingTime ./ baseline.settling_time;

normForce = ...
    T.peakForce ./ F_act_max;


%% =========================================================
% Weighted Cost Function
% ==========================================================

ObjectiveScore = ...
    w_heave      .* normHeave + ...
    w_pitch      .* normPitch + ...
    w_heaveAccel .* normHeaveAccel + ...
    w_pitchAccel .* normPitchAccel + ...
    w_settling   .* normSettling + ...
    w_force      .* normForce;


%% =========================================================
% Find Optimal Gain
% ==========================================================

[bestScore, bestIndex] = min(ObjectiveScore);

optimal_gain = ...
    T.Gain_Nsm(bestIndex);


%% =========================================================
% Extract Optimal Metrics
% ==========================================================

optimal_peak_heave = ...
    T.peakHeave(bestIndex);

optimal_peak_pitch = ...
    T.peakPitch(bestIndex);

optimal_rms_heave_accel = ...
    T.rmsHeaveAccel(bestIndex);

optimal_rms_pitch_accel = ...
    T.rmsPitchAccel(bestIndex);

optimal_settling_time = ...
    T.settlingTime(bestIndex);

optimal_peak_force = ...
    T.peakForce(bestIndex);

optimal_rms_force = ...
    T.meanRMSForce(bestIndex);

optimal_saturation = ...
    T.maxSaturation(bestIndex);


%% =========================================================
% Improvement vs Passive
% ==========================================================

heave_improvement = ...
    100 * ...
    (baseline.peak_heave_mm - optimal_peak_heave) ...
    / baseline.peak_heave_mm;

pitch_improvement = ...
    100 * ...
    (baseline.peak_pitch_deg - optimal_peak_pitch) ...
    / baseline.peak_pitch_deg;

heave_accel_improvement = ...
    100 * ...
    (baseline.rms_heave_accel - optimal_rms_heave_accel) ...
    / baseline.rms_heave_accel;

pitch_accel_improvement = ...
    100 * ...
    (baseline.rms_pitch_accel - optimal_rms_pitch_accel) ...
    / baseline.rms_pitch_accel;

settling_improvement = ...
    100 * ...
    (baseline.settling_time - optimal_settling_time) ...
    / baseline.settling_time;


%% =========================================================
% Display Results
% ==========================================================

disp('====================================================')
disp('SKYHOOK WEIGHTED GAIN OPTIMIZATION')
disp('====================================================')

fprintf('Optimal C_sky            = %.0f N*s/m\n', ...
    optimal_gain);

fprintf('Objective score          = %.6f\n\n', ...
    bestScore);

fprintf('Peak heave               = %.4f mm\n', ...
    optimal_peak_heave);

fprintf('Peak pitch               = %.5f deg\n', ...
    optimal_peak_pitch);

fprintf('RMS heave acceleration   = %.5f m/s^2\n', ...
    optimal_rms_heave_accel);

fprintf('RMS pitch acceleration   = %.5f deg/s^2\n', ...
    optimal_rms_pitch_accel);

fprintf('Settling time            = %.3f s\n', ...
    optimal_settling_time);

fprintf('Peak actuator force      = %.2f N\n', ...
    optimal_peak_force);

fprintf('Mean RMS actuator force  = %.2f N\n', ...
    optimal_rms_force);

fprintf('Saturation               = %.3f %%\n\n', ...
    optimal_saturation);

fprintf('Peak heave improvement   = %.2f %%\n', ...
    heave_improvement);

fprintf('Peak pitch improvement   = %.2f %%\n', ...
    pitch_improvement);

fprintf('Heave accel improvement  = %.2f %%\n', ...
    heave_accel_improvement);

fprintf('Pitch accel improvement  = %.2f %%\n', ...
    pitch_accel_improvement);

fprintf('Settling improvement     = %.2f %%\n', ...
    settling_improvement);

disp('====================================================')


%% =========================================================
% Add Score to Sweep Table
% ==========================================================

optimizationTable = T;

optimizationTable.ObjectiveScore = ...
    ObjectiveScore;


%% =========================================================
% Save Full Optimization Table
% ==========================================================

csvFile = fullfile( ...
    resultsFolder, ...
    'skyhook_weighted_optimization.csv');

writetable( ...
    optimizationTable, ...
    csvFile);


%% =========================================================
% Save TXT Summary
% ==========================================================

txtFile = fullfile( ...
    resultsFolder, ...
    'skyhook_weighted_optimization.txt');

fid = fopen(txtFile, 'w');

fprintf(fid, ...
    'SKYHOOK WEIGHTED GAIN OPTIMIZATION\n');

fprintf(fid, ...
    '==================================\n\n');

fprintf(fid, ...
    'Weights:\n');

fprintf(fid, ...
    'Peak Heave             = %.2f\n', ...
    w_heave);

fprintf(fid, ...
    'Peak Pitch             = %.2f\n', ...
    w_pitch);

fprintf(fid, ...
    'RMS Heave Acceleration = %.2f\n', ...
    w_heaveAccel);

fprintf(fid, ...
    'RMS Pitch Acceleration = %.2f\n', ...
    w_pitchAccel);

fprintf(fid, ...
    'Settling Time          = %.2f\n', ...
    w_settling);

fprintf(fid, ...
    'Actuator Effort        = %.2f\n\n', ...
    w_force);

fprintf(fid, ...
    'Optimal Gain = %.0f N*s/m\n', ...
    optimal_gain);

fprintf(fid, ...
    'Objective Score = %.6f\n\n', ...
    bestScore);

fprintf(fid, ...
    'Peak Heave = %.4f mm\n', ...
    optimal_peak_heave);

fprintf(fid, ...
    'Peak Pitch = %.5f deg\n', ...
    optimal_peak_pitch);

fprintf(fid, ...
    'RMS Heave Accel = %.5f m/s^2\n', ...
    optimal_rms_heave_accel);

fprintf(fid, ...
    'RMS Pitch Accel = %.5f deg/s^2\n', ...
    optimal_rms_pitch_accel);

fprintf(fid, ...
    'Settling Time = %.3f s\n', ...
    optimal_settling_time);

fprintf(fid, ...
    'Peak Actuator Force = %.2f N\n', ...
    optimal_peak_force);

fprintf(fid, ...
    'Saturation = %.3f %%\n', ...
    optimal_saturation);

fclose(fid);


%% =========================================================
% Save MAT
% ==========================================================

matFile = fullfile( ...
    resultsFolder, ...
    'skyhook_weighted_optimization.mat');

save(matFile, ...
    'optimizationTable', ...
    'optimal_gain', ...
    'bestScore', ...
    'optimal_peak_heave', ...
    'optimal_peak_pitch', ...
    'optimal_rms_heave_accel', ...
    'optimal_rms_pitch_accel', ...
    'optimal_settling_time', ...
    'optimal_peak_force', ...
    'optimal_rms_force', ...
    'optimal_saturation', ...
    'heave_improvement', ...
    'pitch_improvement', ...
    'heave_accel_improvement', ...
    'pitch_accel_improvement', ...
    'settling_improvement');


%% =========================================================
% Plot Objective Score
% ==========================================================

fig = figure( ...
    'Name', ...
    'Skyhook Weighted Optimization', ...
    'NumberTitle', ...
    'off');

plot( ...
    T.Gain_Nsm, ...
    ObjectiveScore, ...
    '-o', ...
    'LineWidth', ...
    1.5);

hold on

plot( ...
    optimal_gain, ...
    bestScore, ...
    'o', ...
    'MarkerSize', ...
    10, ...
    'LineWidth', ...
    2);

grid on

xlabel('C_{sky} [N s/m]')
ylabel('Weighted Objective Score')

title('Skyhook Weighted Gain Optimization')

xline( ...
    optimal_gain, ...
    '--', ...
    sprintf('Optimal = %.0f N s/m', optimal_gain));


%% =========================================================
% Save Plot
% ==========================================================

pngFile = fullfile( ...
    plotsFolder, ...
    'skyhook_weighted_optimization.png');

figFile = fullfile( ...
    plotsFolder, ...
    'skyhook_weighted_optimization.fig');

exportgraphics( ...
    fig, ...
    pngFile, ...
    'Resolution', ...
    300);

savefig(fig, figFile);


%% =========================================================
% Confirmation
% ==========================================================

disp(' ')
disp('Weighted optimization saved successfully.');

fprintf('\nResults:\n');
fprintf('%s\n', txtFile);
fprintf('%s\n', csvFile);
fprintf('%s\n', matFile);

fprintf('\nPlot:\n');
fprintf('%s\n', pngFile);
